// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK {
    
    
    public partial class FamilyMoreDialog {
        
        private Gedcom.UI.GTK.Widgets.FamilyMoreView FamilyMoreView;
        
        private Gtk.Button button1142;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.FamilyMoreDialog
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.FamilyMoreDialog";
            this.Title = Mono.Unix.Catalog.GetString("FamilyMoreDialog");
            // Internal child Gedcom.UI.GTK.FamilyMoreDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.FamilyMoreView = new Gedcom.UI.GTK.Widgets.FamilyMoreView();
            this.FamilyMoreView.Events = ((Gdk.EventMask)(256));
            this.FamilyMoreView.Name = "FamilyMoreView";
            w1.Add(this.FamilyMoreView);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(w1[this.FamilyMoreView]));
            w2.Position = 0;
            w2.Padding = ((uint)(6));
            // Internal child Gedcom.UI.GTK.FamilyMoreDialog.ActionArea
            Gtk.HButtonBox w3 = this.ActionArea;
            w3.Events = ((Gdk.EventMask)(256));
            w3.Name = "Gedcom.UI.GTK.FamilyMoreDialog_ActionArea";
            w3.Spacing = 6;
            w3.BorderWidth = ((uint)(5));
            w3.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child Gedcom.UI.GTK.FamilyMoreDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button1142 = new Gtk.Button();
            this.button1142.CanDefault = true;
            this.button1142.CanFocus = true;
            this.button1142.Name = "button1142";
            this.button1142.UseStock = true;
            this.button1142.UseUnderline = true;
            this.button1142.Label = "gtk-close";
            this.AddActionWidget(this.button1142, -7);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.button1142]));
            w4.Expand = false;
            w4.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 663;
            this.DefaultHeight = 490;
            this.Show();
            this.FamilyMoreView.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnFamilyMoreView_SelectNewNote);
            this.FamilyMoreView.MoreFactInformation += new System.EventHandler<Gedcom.UI.Common.FactArgs>(this.OnFamilyMoreView_MoreFactInformation);
            this.FamilyMoreView.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnFamilyMoreView_ShowSourceCitation);
            this.FamilyMoreView.ShowScrapBook += new System.EventHandler<Gedcom.UI.Common.ScrapBookArgs>(this.OnFamilyMoreView_ShowScrapBook);
        }
    }
}
