// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK {
    
    
    public partial class ScrapBookDialog {
        
        private Gedcom.UI.GTK.Widgets.ScrapBookView ScrapBookList;
        
        private Gtk.Button CloseButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.ScrapBookDialog
            this.Name = "Gedcom.UI.GTK.ScrapBookDialog";
            this.Title = Mono.Unix.Catalog.GetString("Scrapbook");
            // Internal child Gedcom.UI.GTK.ScrapBookDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.ScrapBookList = new Gedcom.UI.GTK.Widgets.ScrapBookView();
            this.ScrapBookList.Events = ((Gdk.EventMask)(256));
            this.ScrapBookList.Name = "ScrapBookList";
            this.ScrapBookList.ShowRecordList = true;
            this.ScrapBookList.ShowFileList = true;
            w1.Add(this.ScrapBookList);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(w1[this.ScrapBookList]));
            w2.Position = 0;
            // Internal child Gedcom.UI.GTK.ScrapBookDialog.ActionArea
            Gtk.HButtonBox w3 = this.ActionArea;
            w3.Name = "dialog1_ActionArea";
            w3.Spacing = 6;
            w3.BorderWidth = ((uint)(5));
            w3.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.CloseButton = new Gtk.Button();
            this.CloseButton.CanDefault = true;
            this.CloseButton.CanFocus = true;
            this.CloseButton.Name = "CloseButton";
            this.CloseButton.UseStock = true;
            this.CloseButton.UseUnderline = true;
            this.CloseButton.Label = "gtk-close";
            this.AddActionWidget(this.CloseButton, -7);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.CloseButton]));
            w4.Expand = false;
            w4.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 530;
            this.DefaultHeight = 301;
            this.Show();
            this.Response += new Gtk.ResponseHandler(this.OnScrapBookDialog_Response);
            this.ScrapBookList.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnScrapBookList_ShowSourceCitation);
            this.ScrapBookList.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnScrapBookList_SelectNewNote);
        }
    }
}
