// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK {
    
    
    public partial class FileSelectorDialog {
        
        private Gtk.Button button49;
        
        private Gtk.Button ActionButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.FileSelectorDialog
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.FileSelectorDialog";
            this.Title = Mono.Unix.Catalog.GetString("FileSelectorDialog");
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.DestroyWithParent = true;
            this.HasSeparator = false;
            // Internal child Gedcom.UI.GTK.FileSelectorDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.Spacing = 6;
            w1.BorderWidth = ((uint)(2));
            // Internal child Gedcom.UI.GTK.FileSelectorDialog.ActionArea
            Gtk.HButtonBox w2 = this.ActionArea;
            w2.Events = ((Gdk.EventMask)(256));
            w2.Name = "Gedcom.UI.GTK.FileSelectorDialog_ActionArea";
            w2.Spacing = 6;
            w2.BorderWidth = ((uint)(5));
            w2.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child Gedcom.UI.GTK.FileSelectorDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button49 = new Gtk.Button();
            this.button49.CanDefault = true;
            this.button49.CanFocus = true;
            this.button49.Name = "button49";
            this.button49.UseStock = true;
            this.button49.UseUnderline = true;
            this.button49.Label = "gtk-cancel";
            this.AddActionWidget(this.button49, -6);
            Gtk.ButtonBox.ButtonBoxChild w3 = ((Gtk.ButtonBox.ButtonBoxChild)(w2[this.button49]));
            w3.Expand = false;
            w3.Fill = false;
            // Container child Gedcom.UI.GTK.FileSelectorDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.ActionButton = new Gtk.Button();
            this.ActionButton.CanDefault = true;
            this.ActionButton.CanFocus = true;
            this.ActionButton.Name = "ActionButton";
            this.ActionButton.UseStock = true;
            this.ActionButton.UseUnderline = true;
            this.ActionButton.Label = "gtk-open";
            this.AddActionWidget(this.ActionButton, 0);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(w2[this.ActionButton]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 612;
            this.DefaultHeight = 159;
            this.Show();
            this.Response += new Gtk.ResponseHandler(this.OnResponse);
        }
    }
}
