// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK {
    
    
    public partial class FactDetailDialog {
        
        private Gedcom.UI.GTK.Widgets.FactDetailView FactDetails;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.FactDetailDialog
            this.Name = "Gedcom.UI.GTK.FactDetailDialog";
            this.Title = Mono.Unix.Catalog.GetString("Event / Fact Detail");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child Gedcom.UI.GTK.FactDetailDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.FactDetails = new Gedcom.UI.GTK.Widgets.FactDetailView();
            this.FactDetails.Events = ((Gdk.EventMask)(256));
            this.FactDetails.Name = "FactDetails";
            w1.Add(this.FactDetails);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(w1[this.FactDetails]));
            w2.Position = 0;
            w2.Padding = ((uint)(6));
            // Internal child Gedcom.UI.GTK.FactDetailDialog.ActionArea
            Gtk.HButtonBox w3 = this.ActionArea;
            w3.Name = "dialog1_ActionArea";
            w3.Spacing = 6;
            w3.BorderWidth = ((uint)(5));
            w3.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-close";
            this.AddActionWidget(this.buttonOk, -7);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.buttonOk]));
            w4.Expand = false;
            w4.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 637;
            this.DefaultHeight = 497;
            this.Show();
            this.FactDetails.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnFactDetails_ShowSourceCitation);
            this.FactDetails.ShowScrapBook += new System.EventHandler<Gedcom.UI.Common.ScrapBookArgs>(this.OnFactDetails_ShowScrapBook);
            this.FactDetails.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnFactDetails_SelectNewNote);
        }
    }
}
