// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK {
    
    
    public partial class NameDialog {
        
        private Gedcom.UI.GTK.Widgets.NameView ContentNameView;
        
        private Gtk.Button buttonCancel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.NameDialog
            this.Name = "Gedcom.UI.GTK.NameDialog";
            this.Title = Mono.Unix.Catalog.GetString("Name(s)");
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child Gedcom.UI.GTK.NameDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.ContentNameView = new Gedcom.UI.GTK.Widgets.NameView();
            this.ContentNameView.Events = ((Gdk.EventMask)(256));
            this.ContentNameView.Name = "ContentNameView";
            w1.Add(this.ContentNameView);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(w1[this.ContentNameView]));
            w2.Position = 0;
            // Internal child Gedcom.UI.GTK.NameDialog.ActionArea
            Gtk.HButtonBox w3 = this.ActionArea;
            w3.Name = "dialog1_ActionArea";
            w3.Spacing = 6;
            w3.BorderWidth = ((uint)(5));
            w3.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-close";
            this.AddActionWidget(this.buttonCancel, -7);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.buttonCancel]));
            w4.Expand = false;
            w4.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 468;
            this.DefaultHeight = 323;
            this.Show();
            this.ContentNameView.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnContentNameView_ShowSourceCitation);
            this.ContentNameView.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnContentNameView_SelectNewNote);
        }
    }
}
