// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK {
    
    
    public partial class NoteListDialog {
        
        private Gedcom.UI.GTK.Widgets.NotesView NotesListView;
        
        private Gtk.Button button1456;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.NoteListDialog
            this.Name = "Gedcom.UI.GTK.NoteListDialog";
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child Gedcom.UI.GTK.NoteListDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.NotesListView = new Gedcom.UI.GTK.Widgets.NotesView();
            this.NotesListView.Events = ((Gdk.EventMask)(256));
            this.NotesListView.Name = "NotesListView";
            this.NotesListView.DataNotes = false;
            this.NotesListView.ListOnly = true;
            this.NotesListView.NoteOnly = false;
            w1.Add(this.NotesListView);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(w1[this.NotesListView]));
            w2.Position = 0;
            // Internal child Gedcom.UI.GTK.NoteListDialog.ActionArea
            Gtk.HButtonBox w3 = this.ActionArea;
            w3.Name = "dialog1_ActionArea";
            w3.Spacing = 6;
            w3.BorderWidth = ((uint)(5));
            w3.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button1456 = new Gtk.Button();
            this.button1456.CanFocus = true;
            this.button1456.Name = "button1456";
            this.button1456.UseStock = true;
            this.button1456.UseUnderline = true;
            this.button1456.Label = "gtk-help";
            this.AddActionWidget(this.button1456, -11);
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-new";
            this.AddActionWidget(this.buttonCancel, -5);
            Gtk.ButtonBox.ButtonBoxChild w5 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.buttonCancel]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseUnderline = true;
            // Container child buttonOk.Gtk.Container+ContainerChild
            Gtk.Alignment w6 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            Gtk.HBox w7 = new Gtk.HBox();
            w7.Spacing = 2;
            // Container child GtkHBox2.Gtk.Container+ContainerChild
            Gtk.Image w8 = new Gtk.Image();
            w8.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Button, 20);
            w7.Add(w8);
            // Container child GtkHBox2.Gtk.Container+ContainerChild
            Gtk.Label w10 = new Gtk.Label();
            w10.LabelProp = Mono.Unix.Catalog.GetString("_Select");
            w10.UseUnderline = true;
            w7.Add(w10);
            w6.Add(w7);
            this.buttonOk.Add(w6);
            this.AddActionWidget(this.buttonOk, -10);
            Gtk.ButtonBox.ButtonBoxChild w14 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.buttonOk]));
            w14.Position = 2;
            w14.Expand = false;
            w14.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
