// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK {
    
    
    public partial class SourceListDialog {
        
        private Gedcom.UI.GTK.Widgets.SourceList SourceList;
        
        private Gtk.Button button50;
        
        private Gtk.Button SelectSourceButton;
        
        private Gtk.Button button93;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.SourceListDialog
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.SourceListDialog";
            this.Title = Mono.Unix.Catalog.GetString("SourceListDialog");
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.HasSeparator = false;
            // Internal child Gedcom.UI.GTK.SourceListDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.SourceList = new Gedcom.UI.GTK.Widgets.SourceList();
            this.SourceList.Events = ((Gdk.EventMask)(256));
            this.SourceList.Name = "SourceList";
            w1.Add(this.SourceList);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(w1[this.SourceList]));
            w2.Position = 0;
            // Internal child Gedcom.UI.GTK.SourceListDialog.ActionArea
            Gtk.HButtonBox w3 = this.ActionArea;
            w3.Events = ((Gdk.EventMask)(256));
            w3.Name = "Gedcom.UI.GTK.SourceListDialog_ActionArea";
            w3.Spacing = 6;
            w3.BorderWidth = ((uint)(5));
            // Container child Gedcom.UI.GTK.SourceListDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button50 = new Gtk.Button();
            this.button50.CanDefault = true;
            this.button50.CanFocus = true;
            this.button50.Name = "button50";
            this.button50.UseStock = true;
            this.button50.UseUnderline = true;
            this.button50.Label = "gtk-help";
            this.AddActionWidget(this.button50, -11);
            // Container child Gedcom.UI.GTK.SourceListDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.SelectSourceButton = new Gtk.Button();
            this.SelectSourceButton.CanDefault = true;
            this.SelectSourceButton.CanFocus = true;
            this.SelectSourceButton.Name = "SelectSourceButton";
            this.SelectSourceButton.UseStock = true;
            this.SelectSourceButton.UseUnderline = true;
            this.SelectSourceButton.Label = "gtk-new";
            this.AddActionWidget(this.SelectSourceButton, -5);
            Gtk.ButtonBox.ButtonBoxChild w5 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.SelectSourceButton]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child Gedcom.UI.GTK.SourceListDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button93 = new Gtk.Button();
            this.button93.CanDefault = true;
            this.button93.CanFocus = true;
            this.button93.Name = "button93";
            this.button93.UseUnderline = true;
            // Container child button93.Gtk.Container+ContainerChild
            Gtk.Alignment w6 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            Gtk.HBox w7 = new Gtk.HBox();
            w7.Spacing = 2;
            // Container child GtkHBox2.Gtk.Container+ContainerChild
            Gtk.Image w8 = new Gtk.Image();
            w8.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Button, 20);
            w7.Add(w8);
            // Container child GtkHBox2.Gtk.Container+ContainerChild
            Gtk.Label w10 = new Gtk.Label();
            w10.LabelProp = Mono.Unix.Catalog.GetString("_Select");
            w10.UseUnderline = true;
            w7.Add(w10);
            w6.Add(w7);
            this.button93.Add(w6);
            this.AddActionWidget(this.button93, -10);
            Gtk.ButtonBox.ButtonBoxChild w14 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.button93]));
            w14.Position = 2;
            w14.Expand = false;
            w14.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
