// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK {
    
    
    public partial class IndividualMoreDialog {
        
        private Gedcom.UI.GTK.Widgets.IndividualView IndividualView;
        
        private Gtk.Button button79;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.IndividualMoreDialog
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.IndividualMoreDialog";
            this.Title = Mono.Unix.Catalog.GetString("IndividualMoreDialog");
            // Internal child Gedcom.UI.GTK.IndividualMoreDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.IndividualView = new Gedcom.UI.GTK.Widgets.IndividualView();
            this.IndividualView.Events = ((Gdk.EventMask)(256));
            this.IndividualView.Name = "IndividualView";
            w1.Add(this.IndividualView);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(w1[this.IndividualView]));
            w2.Position = 0;
            // Internal child Gedcom.UI.GTK.IndividualMoreDialog.ActionArea
            Gtk.HButtonBox w3 = this.ActionArea;
            w3.Events = ((Gdk.EventMask)(256));
            w3.Name = "Gedcom.UI.GTK.IndividualMoreDialog_ActionArea";
            w3.Spacing = 6;
            w3.BorderWidth = ((uint)(5));
            w3.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child Gedcom.UI.GTK.IndividualMoreDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button79 = new Gtk.Button();
            this.button79.CanDefault = true;
            this.button79.CanFocus = true;
            this.button79.Name = "button79";
            this.button79.UseStock = true;
            this.button79.UseUnderline = true;
            this.button79.Label = "gtk-close";
            this.AddActionWidget(this.button79, -7);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.button79]));
            w4.Expand = false;
            w4.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 663;
            this.DefaultHeight = 532;
            this.Show();
            this.IndividualView.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnIndividualView_ShowSourceCitation);
            this.IndividualView.ShowScrapBook += new System.EventHandler<Gedcom.UI.Common.ScrapBookArgs>(this.OnIndividualView_ShowScrapBook);
            this.IndividualView.ShowName += new System.EventHandler<Gedcom.UI.Common.IndividualArgs>(this.OnIndividualView_ShowName);
            this.IndividualView.DeleteIndividual += new System.EventHandler<Gedcom.UI.Common.IndividualArgs>(this.OnIndividualView_DeleteIndividual);
            this.IndividualView.MoreFactInformation += new System.EventHandler<Gedcom.UI.Common.FactArgs>(this.OnIndividualView_MoreFactInformation);
            this.IndividualView.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnIndividualView_SelectNewNote);
        }
    }
}
