var gfc_Hn=osapi,gfc_In="ceil";gfc_1[gfc_].share=gfc_5c(23,function(){gfc_$m();return gfc_d});gfc_1f[gfc_].ceil=gfc_5c(19,function(){gfc_ua(this,gfc_j[gfc_In](this[gfc_o]));gfc_Oa(this,gfc_j[gfc_In](this[gfc_J]));return this});gfc_1[gfc_].Li=gfc_5c(18,function(){var a=this.yd;a.valid?(this.d=this.Cg(this.yd),this.Mh(a[gfc_Qb])):(this.yd=gfc_c,this.render(a.actions,a[gfc_Qb],a.params));this.Bg()});gfc_1[gfc_].Cf=gfc_5c(14,function(){return this.Eb.pop()});
gfc_1[gfc_].ni=gfc_5c(5,function(a,b,c){return a?c<b?[]:a[gfc_hb](gfc_j.min(b,a[gfc_m]),gfc_j.min(c,a[gfc_m])):[]});
var gfc_Jn=function(a){return a=gfc_g.friendconnect_serverBase+"/friendconnect/favicon?url="+escape(a)},gfc_7=function(a,b,c){this.Ea();this.Pq();var d=new gfc_O;d.set("members",{action:this.Yt,callback:this.Vs});d.set("member-page",{action:this.Xt,callback:this.Us});d.set("blocked-member-page",{action:this.Rt,callback:this.Qs});d.set("profile-friends-page",{action:this.cu,callback:this.Zs});d.set("sitesData",{action:this.ku,callback:this.dt});d.set("viewerFriends",{action:this.pu,callback:this.ft});
d.set("profileData",{action:this.bu,callback:this.Ys});d.set("blockUser",{action:this.Qt,callback:this.Ps});d.set("unblockUser",{action:this.nu,callback:this.et});d.set("profileFriends",{action:this.du,callback:this.$s});d.set("activityData",{action:this.Lf,callback:this.ld});d.set("sendFriendRequest",{action:this.ju,callback:this.bt});d.set("sendFriendRequestResponse",{action:this.Ut,callback:this.Tl});d.set("deleteActivity",{action:this.Mf,callback:this.ld});d.set("requestAndProcessViewerNumWaitingMessages",
{action:this.qu,callback:this.ht});d.set("requestPromo",{action:this.eu,callback:this.at});this.hb=gfc_c;this.Gw=new gfc_hn("fc-members-options-menu",gfc_L(this.ss,this),gfc_L(this.rs,this),gfc_L(this.ts,this),0,gfc_g.friendconnect_serverBase,this.f("ENDCAP_LINK_COLOR")||"0000cc",this.f("CONTENT_TEXT_COLOR")||"000000");this.uv=gfc_d;this.Ba=10;this.yf=15;this.Um=10;var e=gfc_1g(gfc_Ng()),f=gfc_Kn;this.Xb=3;this.rc=8;this.qm=gfc_c;this.pa=this.rc*this.Xb;this.slimTopCapHeight=19;this.tinyTopCapHeight=
8;this.isMessagingEnabled=a;this.isPromosEnabled=b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=gfc_c;this.Pb=new gfc_dn;this.Gh()&&(a=(a=this.f(f.FACE_SIZE))?gfc_ha(a):32,a+=6,this.Xb=gfc_j[gfc_ob]((e[gfc_o]-10)/a),e=340,e=this.f(f.HEIGHT),b=this.f(f.NUMBER_ROWS),f=27,b?(this.rc=gfc_ha(b),e=this.rc*a,this.qm=e+f):e&&(e=gfc_ha(e)-96,this.rc=gfc_j.max(2,gfc_j[gfc_ob](e/a)),this.qm=this.rc*a+f),this.pa=this.rc*this.Xb);gfc_1[gfc_A](this,d)};gfc_7.inherits(gfc_1);
gfc_Ea(gfc_7[gfc_],function(){gfc_7.i[gfc_C][gfc_A](this);gfc_Mm("start");var a=gfc_e[gfc_n][gfc_Ub](),b=gfc_la();(a=b.profileId||a.profileId)?(b={},b[gfc_h[gfc_t][gfc_H].ID]=a,a=new gfc_h[gfc_t](b),this.render(["profileData","profileFriends","activityData"],"profile",{person:a})):(a=["members","viewerFriends"],this.isMessagingEnabled&&a[gfc_l]("requestAndProcessViewerNumWaitingMessages"),this.isPromosEnabled&&!this.Ib()&&a[gfc_l]("requestPromo"),this.render(a,"faces"))});gfc_7[gfc_].e={};
gfc_7[gfc_].Ea=function(){this.e.MSG_SITE_MEMBERS="Members";this.e.MSG_BE_THE_FIRST="Be the first!";this.e.MSG_NO_SITE_MEMBERS="There are no members yet.";this.e.MSG_ALL_SITE_MEMBERS="All Members";this.e.MSG_ALL_BLOCKED_MEMBERS="All Blocked Members";this.e.MSG_NO_BLOCKED_MEMBERS="You have not blocked any members";this.e.MSG_YOUR_FRIENDS="Your Friends";this.e.MSG_ALL_YOUR_FRIENDS="All Your Friends";this.e.MSG_JFJ="Join and connect with others!";this.e.MSG_MANAGE="Manage members";this.e.MSG_SETTINGS=
"Settings";this.e.MSG_OPTIONS="Options";this.e.MSG_INVITE="Invite";this.e.MSG_MEMBERS_SHARE="Share this page";this.e.MSG_BACK="Back";this.e.MSG_BACK_TO_TOP="Home";this.e.MSG_VIEW_MY_PROFILE="View my profile";this.e.MSG_ABOUT_ME="About me";this.e.MSG_MORE="More \u00bb";this.e.MSG_SHOW_BLOCKED="Show blocked members \u00bb";this.e.MSG_SHOW_ALL="\u00ab Show all members";this.e.MSG_INVITE_YOUR_FRIENDS="Invite your friends";this.e.MSG_LINK_IN_NETWORKS="Link in your social networks";this.e.MSG_ACTIVITIES=
"Activities";this.e.MSG_ALL_ACTIVITIES="More activities";this.e.MSG_DELETE_THIS="Delete";this.e.MSG_SITES="Sites I've joined";this.e.MSG_ALL_SITES="More sites I've joined";this.e.MSG_LINKS="Links";this.e.MSG_ALL_LINKS="More links";this.e.MSG_NO_ACTIVITIES="No activities to show";this.e.MSG_ADD_AS_FRIEND="Add as friend";this.e.MSG_SEND_MESSAGE="Send a message";this.e.MSG_BLOCK_USER="Block this user";this.e.MSG_UNBLOCK_USER="Unblock this user";this.e.MSG_USER_IS_ADMIN="Administrator";this.e.MSG_JOIN=
"Join this site";this.e.MSG_OR="or";this.e.MSG_SIGN_IN="Sign in";this.e.MSG_SIGN_OUT="Sign out";this.e.MSG_PREVIOUS="\u00ab Previous";this.e.MSG_NEXT="Next \u00bb";this.e.MSG_NEWER="\u00ab Newer";this.e.MSG_OLDER="Older \u00bb";this.e.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Accept all";this.e.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Friend Connect sites.";this.e.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Friend Connect sites.";this.e.MSG_HELP_BLOCKMEMBER=
"Blocking a visitor removes them from the members list and prevents them from interacting with other visitors on your site";this.e.MSG_INVITATION="Invitation:";this.e.MSG_SEND="Send";this.e.MSG_BLOCK="Block";this.e.MSG_IGNORE="Ignore";this.e.MSG_CANCEL="Cancel";this.e.MSG_SITE_SETTINGS="Site settings";this.e.MSG_INVITE_FRIENDS="Invite friends";this.e.MSG_ABOUT_FC="About Friend Connect";this.e.MSG_ALREADY_MEMBER="Already a member?";this.e.MSG_EDIT_PROFILE="Edit profile"};gfc_7[gfc_].sa={};
gfc_7[gfc_].Pq=function(){this.sa.MSG_SITE_MEMBERS="Followers";this.sa.MSG_NO_SITE_MEMBERS="There are no followers yet.";this.sa.MSG_SHOW_BLOCKED="Show blocked followers \u00bb";this.sa.MSG_SHOW_ALL="\u00ab Show all followers";this.sa.MSG_ALL_SITE_MEMBERS="All Followers";this.sa.MSG_ALL_BLOCKED_MEMBERS="All Blocked Followers";this.sa.MSG_NO_BLOCKED_MEMBERS="You have not blocked any followers";this.sa.MSG_LIKE_THIS_SITE="Like this blog?";this.sa.MSG_JOIN="Follow";this.sa.MSG_BACK_TO_TOP="Members";
this.sa.MSG_JFJ="Follow and connect with your friends!";this.sa.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Following blogs and Friend Connect sites.";this.sa.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Following blogs and Friend Connect sites."};
gfc_7[gfc_].L=function(a,b){var c=gfc_b;if(b[gfc_D]&&b[gfc_D].person){var d={},e=b[gfc_D].person[gfc_Mb]()+" is your friend";d.MSG_IS_FRIEND=e;e="You have invited "+(b[gfc_D].person[gfc_Mb]()+" to be your friend");d.MSG_IS_INVITED=e;e=b[gfc_D].person[gfc_Mb]()+"'s friends";d.MSG_PROFILE_FRIENDS=e;e="All "+(b[gfc_D].person[gfc_Mb]()+"'s friends");d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.h(a,f,d[f])}b.invitedBy&&b.invitedBy[gfc_Mb]()&&(d=gfc_i[gfc_o]?gfc_i[gfc_o]:gfc_i[gfc_Pb][gfc_db]+2,c=(d-
135)/8,d=(d-175)/8,c="View "+(gfc_Am(b.invitedBy[gfc_Mb](),c)+"'s profile"),d=gfc_Am(b.invitedBy[gfc_Mb](),d)+" invited you to this site",this.h(a,"MSG_VIEW_INVITER_PROFILE",c),this.h(a,"MSG_INVITED_YOU",d),this.uv=gfc_b,c=gfc_d);d=this.numWaitingMessages+" messages waiting for you.";this.isMessagingEnabled&&0<this.numWaitingMessages&&(c=gfc_d,this.h(a,"showWaitingMessages",gfc_b),this.isMessagingEnabled&&(this.h(a,"MSG_NUM_WAITING_MESSAGES",d),this.h(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING","View messages")));
b.friendRequests&&(0<b.friendRequests[gfc_$a]()&&(c=gfc_d),d=1==b.friendRequests[gfc_$a]()?"New friend request \u00bb":"New friend requests ("+(b.friendRequests[gfc_$a]()+") \u00bb"),this.h(a,"MSG_NEW_FRIEND_REQUESTS",d));if(this.hb){if(this.bl(this.hb.themeId))for(f in this.sa)this.h(a,f,this.sa[f]);this.hb.signInPrompt&&this.h(a,"MSG_JOIN",this.hb.signInPrompt);this.hb.signOutPrompt&&this.h(a,"MSG_SIGN_OUT",this.hb.signOutPrompt)}this.h(a,"isViewerAdmin",b.isViewerAdmin);this.h(a,"isMessagingEnabled",
this.isMessagingEnabled);this.h(a,"acceptMessages",this.vn);this.h(a,"isViewingSelf",b.viewer&&b[gfc_D]&&b[gfc_D].person&&b.viewer[gfc_z]()==b[gfc_D].person[gfc_z]());d=gfc_d;if(b.owner&&(e=b.owner[gfc_I]("profileExtensions")))for(f in e)d=gfc_b;this.h(a,"communityHasProfile",d);this.h(a,"promoHtml",c?this.promoHtml:gfc_c);this.h(a,"insertHtml",function(a,b){gfc_wa(a,b)})};gfc_7[gfc_].bl=function(a){return"blogger"==a};
gfc_7[gfc_].Sg=function(a,b,c,d){gfc_8m({id:a,text:b,version:this.bl(this.hb.themeId)?1:gfc_c,style:c},d)};
gfc_7[gfc_].Q=function(a){function b(b,c){d.h(a,b,gfc_L(c,d))}this.h(a,"facesPerRow",this.Xb);for(var c in this.e)this.h(a,c,this.e[c]);var d=this;b("getThumbnail",this.zc);b("map",this.map);b("elide",gfc_Am);b("safeSlice",this.ni);b("showAllActivities",this.fv);b("transformActivity",this.kc);b("nextActivities",this.Tr);b("previousActivities",this.Cs);b("showAllLinks",this.hv);b("transformLink",this.Tv);b("nextLinks",this.Xr);b("previousLinks",this.Es);b("showAllSites",this.kv);b("transformSite",
this.Uv);b("nextSites",this.ds);b("previousSites",this.Ks);b("showAllMembers",this.iv);b("showBlockedMembers",this.mv);b("showUnblockedMembers",this.Dv);b("nextMembers",this.Yr);b("nextBlockedMembers",this.Ur);b("previousMembers",this.Fs);b("previousBlockedMembers",this.Ds);b("showAllProfileFriends",this.jv);b("nextProfileFriends",this.cs);b("previousProfileFriends",this.Js);b("showAllViewerFriends",this.lv);b("nextViewerFriends",this.es);b("previousViewerFriends",this.Ls);b("isHome",this.Dh);b("goBack",
this.hh);b("goBackToHome",this.wv);b("invite",this.invite);b("editSettings",this.Ab);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.ln);b("blockUser",this.hj);b("unblockUser",this.Xv);b("goToInviteFriend",this.Zp);b("sendMessageDialog",this.Eu);b("goToBlockMember",this.Yp);b("goToEditProfile",this.Ab);b("goToViewerProfile",this.$p);b("sendInvite",this.Du);b("blockMember",this.Nn);b("acceptFriendRequest",this.un);b("ignoreFriendRequest",this.Oq);b("viewFriendRequests",this.ew);
b("acceptAllFriendRequests",this.tn);b("numPreviewFriends",this.Ep);b("numPreviewMembers",this.Fp);b("showInvitedBy",this.Mp)};
gfc_7[gfc_].uk=function(a){var a=gfc_j.max(1,a?this.rc-1:this.rc),b=this.d[gfc_q].members?this.d[gfc_q].members[gfc_$a]():0,c=this.d[gfc_q].friends?this.d[gfc_q].friends[gfc_$a]():0,b=gfc_j[gfc_In](b/this.Xb),c=gfc_j[gfc_In](c/this.Xb);b>gfc_j[gfc_In](a/2)?c>gfc_j[gfc_ob](a/2)?(b=gfc_j[gfc_In](a/2),c=gfc_j[gfc_ob](a/2)):b=gfc_j.max(0,a-c):c>gfc_j[gfc_ob](a/2)&&(c=gfc_j.max(0,a-b));b*=this.Xb;c*=this.Xb;return a={numMembers:b,numFriends:c}};gfc_7[gfc_].Fp=function(a){return this.uk(a).numMembers};
gfc_7[gfc_].Ep=function(a){return this.uk(a).numFriends};gfc_7[gfc_].Xt=function(a,b){var c=gfc_h[gfc_G](),d={},e=gfc_h[gfc_x][gfc_sc];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_C];d[e.MAX]=b.pageSize?b.pageSize:this.pa;var f=[gfc_h[gfc_t][gfc_H].ID,gfc_h[gfc_t][gfc_H][gfc_2a],gfc_h[gfc_t][gfc_H][gfc_Pc]];d[e[gfc_vc]]=f;d[gfc_h[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_h.EscapeType.NONE;c.add(c[gfc_4b](gfc_3d(),d),"ownerFriends");c[gfc_B](a)};
gfc_7[gfc_].Us=function(a){this.d[gfc_q].members=a.get("ownerFriends")[gfc_r]()};gfc_7[gfc_].Rt=function(a,b){var c=gfc_h[gfc_G](),d={},e=gfc_h[gfc_x][gfc_sc];d[e.FIRST]=b[gfc_C];d[e.MAX]=b.pageSize?b.pageSize:this.pa;d[gfc_h[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_h.EscapeType.NONE;e={};e[gfc_h[gfc_Xa][gfc_H][gfc_Lb]]=gfc_h[gfc_Xa].PersonId.OWNER;e[gfc_h[gfc_Xa][gfc_H][gfc_qb]]="BLOCKED";e[gfc_h[gfc_Xa][gfc_H][gfc_1a]]=1;e=gfc_h[gfc_Yc](e);c.add(c[gfc_4b](e,d),"blockedMembers");c[gfc_B](a)};
gfc_7[gfc_].Qs=function(a){this.d[gfc_q].blockedMembers=a.get("blockedMembers")[gfc_r]()};gfc_7[gfc_].cu=function(a,b){var c=gfc_h[gfc_G](),d=b&&b.person&&b.person[gfc_z]()||this.v[gfc_D].person[gfc_z](),e={},f=gfc_h[gfc_x][gfc_sc];e[f.FIRST]=b[gfc_C];e[f.MAX]=b.pageSize?b.pageSize:this.pa;d=this.Dl(d);e[gfc_h[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_h.EscapeType.NONE;c.add(c[gfc_4b](d,e),"profileFriends");c[gfc_B](a)};
gfc_7[gfc_].Dl=function(a){var b={};b[gfc_h[gfc_Xa][gfc_H][gfc_Lb]]=a;b[gfc_h[gfc_Xa][gfc_H][gfc_qb]]="FRIENDS";b[gfc_h[gfc_Xa][gfc_H][gfc_1a]]=1;return gfc_h[gfc_Yc](b)};gfc_7[gfc_].Zs=function(a){this.d[gfc_q][gfc_D].friends=a.get("profileFriends")[gfc_r]()};gfc_7[gfc_].aj=function(a){for(var b=gfc_h[gfc_q].getDataContext(),c=0;c<a[gfc_m];c++){var d=a[c],d=b.getDataSet(d);if(!d||d.code)return gfc_d}return gfc_b};
gfc_7[gfc_].Yt=function(a){var b=this.pa,c=!b||24==b;c&&gfc_h[gfc_q]&&this.aj(["ownerFriends","viewer","siteSettings","friendRequests"])?a(gfc_h[gfc_q].getDataContext()[gfc_r]()):(c=gfc_Hn.newBatch(),b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"},c.add("ownerFriends",gfc_Hn.people.get(b)),c.add("viewer",gfc_Hn.people.getViewer()),c.add("siteSettings",gfc_Hn.extensions.get({command:"GetSiteSettings"})),c.add("friendRequests",gfc_Hn.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'})),(b=gfc_la().psinvite)&&c.add("invitedBy",gfc_Hn.extensions.get({command:"DecodeInvitation",params:{token:b}})),c.execute(a))};gfc_7[gfc_].Vs=function(a,b){this.d[gfc_q].members=gfc_Wd(a.ownerFriends,gfc_Rd);this.d[gfc_q].viewer=gfc_Rd(a.viewer);this.Tl(a,b,gfc_b);this.hb=a[gfc_wc];var c=gfc_la();if(c.psinvite&&(this.d[gfc_q].viewer==gfc_c||""==this.d[gfc_q].viewer))a.invitedBy&&(a.invitedBy.nickname=a.invitedBy.displayName),this.d[gfc_q].invitedBy=new gfc_h[gfc_t](a.invitedBy)};
gfc_7[gfc_].pu=function(a,b){var b=b||{},c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_C]||0==b[gfc_C],e=!c||20==c;d&&e&&gfc_h[gfc_q]&&this.aj(["friends","isViewerAdmin"])?a(gfc_h[gfc_q].getDataContext()[gfc_r]()):(d=gfc_Hn.newBatch(),c={userId:"@viewer",groupId:"@friends",count:c},b[gfc_C]&&(c.startIndex=b[gfc_C]),d.add("friends",gfc_Hn.people.get(c)),d.add("isViewerAdmin",gfc_Hn.people.get({userId:"@viewer",groupId:"ADMINS"})),d.execute(a))};
gfc_7[gfc_].ft=function(a){var b=a.friends;b&&!b.error&&(this.d[gfc_q].friends=gfc_Wd(b,gfc_Rd));this.um(a)};gfc_7[gfc_].qu=function(a){var b=gfc_h[gfc_G]();b.add(gfc_Ud("VIEWER"),"numWaitingMessages");b[gfc_B](a)};gfc_7[gfc_].ht=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_r]().numberOfWaitingMessages};
gfc_7[gfc_].eu=function(a){this.log("requesting promo");var b=new gfc_e[gfc_Fb],b=b.getLang()+(b[gfc_mc]()?"_"+b[gfc_mc]():""),c=gfc_h[gfc_G]();c.add(gfc_Jd("GetPromo",{hl:b}),"promo");c[gfc_B](a)};gfc_7[gfc_].at=function(a){this.log("processing promo");if((a=a.get("promo")[gfc_r]())&&-1!=a.promoCode)this.promoCode=a.promoCode,this.promoHtml=a.promoHtml};
gfc_7[gfc_].Cn=function(){for(var a=function(){this.promoHtml=gfc_c;for(var a=gfc_bg("div","fc-promo-main",gfc_R("peg")),b=0;b<a[gfc_m];b++)gfc_4g(a[b],gfc_d);this.X();this.log("Dismissing promo "+this.promoCode);a=gfc_h[gfc_G]();a.add(gfc_Jd("DismissPromo",{promoCode:this.promoCode}));a[gfc_B](gfc_L(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_bg("a","fc-promo-dismiss-link",gfc_R("peg")),c=0;c<b[gfc_m];c++){var d=b[c],e="click";gfc_Uh(d,e);gfc_Mh(d,e,gfc_L(a,
this))}};gfc_7[gfc_].um=function(a){var b=a.isViewerAdmin;if(b&&!b.error)this.d[gfc_q].isViewerAdmin=b.list[gfc_m];else if(a.get&&a.get("isViewerAdmin")&&(a=a.get("isViewerAdmin"))&&!a[gfc_Bb]())this.d[gfc_q].isViewerAdmin=a[gfc_r]()[gfc_$a]()};gfc_7[gfc_].tn=function(a){var b=[];a.each(function(a){a={user:a[gfc_I](goog.opensocial.peoplesense.Invite[gfc_H].INVITER)[gfc_z](),action:"ACCEPT"};b[gfc_l](a)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.zg,this),{friendRequestResponses:b})};
gfc_7[gfc_].wv=function(){this.fa();this.render(["members","viewerFriends"],"faces")};gfc_7[gfc_].un=function(a){a={user:a[gfc_z](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.zg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].ew=function(){this.fa();this.B("friend-requests")};gfc_7[gfc_].ln=function(a){this.Ib()?(this.fa(),this.gw(a)):gfc_Gd(a[gfc_z]())};
gfc_7[gfc_].gw=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_7[gfc_].ku=function(a,b){var c=gfc_h[gfc_G](),d=gfc_h[gfc_x][gfc_sc],e={};e[d.FIRST]=b&&b[gfc_C]?b[gfc_C]:0;var f=this.d[gfc_q][gfc_D].person[gfc_z]();e[d.MAX]=this.Um;c.add(gfc_0d(gfc_h[gfc_Yc]({userId:f}),e),"profileSites");c[gfc_B](a)};gfc_7[gfc_].dt=function(a){this.d[gfc_q][gfc_D].sites=a.get("profileSites")[gfc_r]()};
gfc_7[gfc_].bu=function(a,b){this.d[gfc_q].profile={};var b=b||{},c=b.person,d={},c=c[gfc_z](),e=gfc_h[gfc_G](),f=[gfc_h[gfc_t][gfc_H].ID,gfc_h[gfc_t][gfc_H][gfc_2a],gfc_h[gfc_t][gfc_H][gfc_Pc],gfc_h[gfc_t][gfc_H].ABOUT_ME,gfc_h[gfc_t][gfc_H].URLS,"profileExtensions"],g=gfc_h[gfc_x][gfc_sc];d[g[gfc_vc]]=f;d[gfc_h[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_h.EscapeType.NONE;e.add(e.newFetchPersonRequest(c,d),"profile");e.add(e.newFetchPersonRequest("VIEWER",d),"viewer");e.add(gfc_Zd("VIEWER","ADMINS"),
"isViewerAdmin");e.add(e.newFetchPersonRequest("OWNER",d),"owner");this.hb||e.add(gfc_Td(),"siteSettings");e.add(gfc_Zd(c,"ADMINS"),"isAdmin");e.add(gfc_Zd(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&e.add(gfc_Ud(c),"canMessage");e[gfc_B](a)};
gfc_7[gfc_].Lf=function(a,b){var c=b.person[gfc_z](),d=gfc_h[gfc_Yc]({userId:c}),e=gfc_h[gfc_G]();(this.d[gfc_q].viewer&&c!=this.d[gfc_q].viewer[gfc_z]()||this.Ib())&&e.add(gfc_Yd(b.person[gfc_z](),"VIEWER"),"isProfileFriend");e.add(e[gfc_yb](d,{}),"activities");e[gfc_B](a)};
gfc_7[gfc_].ld=function(a,b){a.get("activities")[gfc_r]()!=gfc_c&&(this.d[gfc_q][gfc_D].activities=a.get("activities")[gfc_r]());var c=a.get("isProfileFriend");c&&b&&this.d[gfc_q].viewer!=gfc_c&&this.d[gfc_q].viewer[gfc_z]()!=b.person[gfc_z]()&&(this.d[gfc_q][gfc_D].isFriend=c[gfc_r]()[gfc_s])};
gfc_7[gfc_].Ys=function(a,b){var c=a.get("profile")[gfc_r]();this.d[gfc_q][gfc_D].person=c;this.d[gfc_q][gfc_D].person.externalProfileUrl=gfc_c;var d=c[gfc_I](gfc_h[gfc_t][gfc_H].URLS),e=[];if(d)for(var f=0;f<d[gfc_m];f++){var g=d[f];"profile"!=g[gfc_I](gfc_h.Url[gfc_H].TYPE)&&"externalProfile"!=g[gfc_I](gfc_h.Url[gfc_H].TYPE)&&e[gfc_l](g);"externalProfile"==g[gfc_I](gfc_h.Url[gfc_H].TYPE)&&(this.d[gfc_q][gfc_D].person.externalProfileUrl=g[gfc_I](gfc_h.Url[gfc_H].ADDRESS))}this.d[gfc_q][gfc_D].links=
new gfc_Ln(e,this.yf,0);this.d[gfc_q].owner=a.get("owner")[gfc_r]();this.d[gfc_q].viewer=a.get("viewer")[gfc_r]();if((d=this.d[gfc_q].viewer)&&b.person[gfc_z]()!=this.d[gfc_q].viewer[gfc_z]())this.d[gfc_q][gfc_D].isAdmin=a.get("isAdmin")[gfc_r](),this.d[gfc_q][gfc_D].isAdmin&&(this.d[gfc_q][gfc_D].isAdmin=this.d[gfc_q][gfc_D].isAdmin[gfc_$a]()),this.d[gfc_q][gfc_D].isBlocked=a.get("isBlocked")[gfc_r](),this.d[gfc_q][gfc_D].isBlocked&&(this.d[gfc_q][gfc_D].isBlocked=this.d[gfc_q][gfc_D].isBlocked[gfc_$a]());
c=c[gfc_I]("profileExtensions");c=this.Pb.rf(c,this.Pb.Di);d=[];for(f in c){e=c[f];g={};g.title=e.title;var h=gfc_d;if("SHORT_TEXT"==e.entryType||"LONG_TEXT"==e.entryType)e[gfc_s]&&e[gfc_s][gfc_cb]&&(g.body=[],g[gfc_Pb][gfc_l](e[gfc_s][gfc_cb]),h=gfc_b);else if(e[gfc_s]&&e[gfc_s].choice&&0<e[gfc_s].choice[gfc_m]){g.body=[];for(h=0;h<e[gfc_s].choice[gfc_m];++h)g[gfc_Pb][gfc_l](e[gfc_s].choice[h][gfc_Lc]);h=gfc_b}h&&d[gfc_l](g)}this.d[gfc_q][gfc_D].profileExtensions=d;this.hb||(this.hb=a.get("siteSettings")[gfc_r]());
this.isMessagingEnabled&&(f=(f=a.get("canMessage"))&&f[gfc_r]().canSendMessage,this.d[gfc_q][gfc_D].canSendMessage=f);this.um(a)};gfc_7[gfc_].hj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_7[gfc_].Xv=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_7[gfc_].map=function(a,b){var c=[],d=gfc_L(function(a,b,c){a[gfc_l](b(c))},this,c,b);a.each(d);return c};gfc_7[gfc_].iv=function(){this.fa();this.B("members-page")};
gfc_7[gfc_].mv=function(){this.fa();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_7[gfc_].Dv=function(){this.Li()};gfc_7[gfc_].Yr=function(a){this.render(["member-page"],"members-page",{start:this.pa+a.getOffset()})};gfc_7[gfc_].Fs=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.pa})};gfc_7[gfc_].Ur=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.pa+a.getOffset()})};
gfc_7[gfc_].Ds=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.pa})};gfc_7[gfc_].lv=function(){this.fa();this.B("viewer-friends-page")};gfc_7[gfc_].es=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.pa+a.getOffset()})};gfc_7[gfc_].Ls=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.pa})};gfc_7[gfc_].jv=function(){this.fa();this.B("profile-friends-page")};
gfc_7[gfc_].cs=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.pa+a.getOffset(),person:this.d[gfc_q][gfc_D].person})};gfc_7[gfc_].Js=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.pa,person:this.d[gfc_q][gfc_D].person})};gfc_7[gfc_].hv=function(){this.fa();this.B("links")};gfc_7[gfc_].Xr=function(a){var b=this.yf+a.getOffset();this.d[gfc_q][gfc_D].links=new gfc_Ln(a.all(),this.yf,b);this.B("links")};
gfc_7[gfc_].Es=function(a){var b=a.getOffset()-this.yf;this.d[gfc_q][gfc_D].links=new gfc_Ln(a.all(),this.yf,b);this.B("links")};gfc_7[gfc_].kv=function(){this.fa();this.B("sites")};gfc_7[gfc_].ds=function(a){this.render(["sitesData"],"sites",{start:this.Um+a.getOffset()})};gfc_7[gfc_].Ks=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.Um})};gfc_7[gfc_].fv=function(){this.fa();this.B("activities")};
gfc_7[gfc_].Tr=function(a){this.render(["activityData"],"activities",{start:this.Ba+a.getOffset()})};gfc_7[gfc_].Cs=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Ba})};gfc_7[gfc_].ff=function(a){this.render(["deleteActivity"],this.d[gfc_Qb],{activity:a})};gfc_7[gfc_].Qt=function(a,b){var c=gfc_h[gfc_G]();c.add(gfc__d(b.person[gfc_z](),["BLOCKED"],[]),"block");this.fd();c[gfc_B](a)};
gfc_7[gfc_].Ps=function(a){if(a=!a.get("block")[gfc_Bb]())this.d[gfc_q][gfc_D].isBlocked=gfc_b};gfc_7[gfc_].nu=function(a,b){var c=gfc_h[gfc_G]();c.add(gfc__d(b.person[gfc_z](),[],["BLOCKED"]),"unblock");this.fd();c[gfc_B](a)};gfc_7[gfc_].et=function(a){if(a=!a.get("unblock")[gfc_Bb]())this.d[gfc_q][gfc_D].isBlocked=gfc_d};
gfc_7[gfc_].Mf=function(a,b){var c=b.activity,d=c[gfc_I](gfc_h[gfc_5b][gfc_H].ID),c=gfc_h[gfc_Yc]({userId:c[gfc_I](gfc_h[gfc_5b][gfc_H][gfc_Lb])}),e=gfc_h[gfc_G]();e.add(gfc_Kd(d),"delete");e.add(e[gfc_yb](c,{}),"activities");e[gfc_B](a)};
gfc_7[gfc_].kc=function(a){var b=gfc_gn,c=function(a){return a=a[gfc_p](/<a/g,"<a target='_top'")},d=gfc_c,e=this.d[gfc_q].viewer;e!=gfc_c&&a[gfc_I](gfc_h[gfc_5b][gfc_H][gfc_Lb])==this.d[gfc_q].viewer[gfc_z]()&&(d=gfc_L(this.ff,this,a));(e=a[gfc_I](gfc_h[gfc_5b][gfc_H].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_g.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_ha(a[gfc_I](gfc_h[gfc_5b][gfc_H].POSTED_TIME))),link:a[gfc_I](gfc_h[gfc_5b][gfc_H].STREAM_URL,{escapeType:"none"}),
siteTitle:a[gfc_I](gfc_h[gfc_5b][gfc_H].STREAM_TITLE,{escapeType:"none"}),innerHTML:c(a[gfc_I](gfc_h[gfc_5b][gfc_H].TITLE,{escapeType:"none"})),body:c(a[gfc_I](gfc_h[gfc_5b][gfc_H].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_7[gfc_].Uv=function(a){var b=gfc_e[gfc_qc].unescapeString,c=gfc_Jn;return{icon:c(a[gfc_I](gfc_h[gfc_t][gfc_H][gfc_cc])),link:a[gfc_I](gfc_h[gfc_t][gfc_H][gfc_cc]),title:b(a[gfc_Mb]())}};
gfc_7[gfc_].Tv=function(a){var b=gfc_e[gfc_qc].unescapeString,c=gfc_Jn,d=a[gfc_I](gfc_h.Url[gfc_H].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_I](gfc_h.Url[gfc_H].LINK_TEXT))||d}};gfc_7[gfc_].du=function(a,b){var c=gfc_h[gfc_G](),d=b.person[gfc_z](),e=gfc_h[gfc_x][gfc_sc],f=this.Dl(d),g={};g[gfc_h[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_h.EscapeType.NONE;c.add(c[gfc_4b](f,g),"friends");f={};f[e.FIRST]=this.Xw;f[e.MAX]=this.Ww;c.add(gfc_0d(gfc_h[gfc_Yc]({userId:d}),f),"profileSites");c[gfc_B](a)};
gfc_7[gfc_].Oq=function(a){a={user:a[gfc_z](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.zg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].zg=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_7[gfc_].ju=function(a,b){var c=b[gfc_D],d=gfc_h[gfc_G]();d.add(gfc_Ld(c[gfc_z](),b[gfc_Jb]),"friendRequest");this.fd();d[gfc_B](a)};gfc_7[gfc_].bt=function(a){a.get("friendRequest")[gfc_Bb]()||(this.d[gfc_q][gfc_D].isInvited=gfc_b)};
gfc_7[gfc_].Ut=function(a,b){var c=gfc_Hn.newBatch(),d=b.friendRequestResponses;c.add("updateFriendRequest",gfc_Hn.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_e[gfc_$b].stringify(d)+"}"}));c.add("friendRequests",gfc_Hn.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.fd();c.execute(a)};gfc_7[gfc_].Zp=function(){this.fa();this.B("invite-friend")};gfc_7[gfc_].Eu=function(a){this.isMessagingEnabled&&(a=a[gfc_I](gfc_h[gfc_t][gfc_H].ID),this.Fu(a))};
gfc_7[gfc_].Fu=function(a){if(this.isMessagingEnabled){var a="/friendconnect/messaging/compose?recipientId="+a,b=570,c=395;gfc_0m(a,""+b,""+c)}};gfc_1[gfc_].vn=function(){var a="/friendconnect/messaging/accept",b=570,c=375;gfc_0m(a,""+b,""+c);return gfc_d};gfc_7[gfc_].Yp=function(){this.fa();this.B("block-member")};gfc_7[gfc_].$p=function(){this.ln(this.d[gfc_q].viewer)};
gfc_7[gfc_].Du=function(a){this.Cf();var a={profile:a},b=gfc_R("inviteMessage");b&&(a.message=gfc_Tf(b));this.render(["sendFriendRequest"],"profile",a)};gfc_7[gfc_].Nn=function(a){this.Cf();this.hj(a)};gfc_7[gfc_].Tl=function(a,b,c){c=c||gfc_d;this.d[gfc_q].friendRequests=gfc_Wd(a.friendRequests,gfc_Nd);b["next-view"]=0<this.d[gfc_q].friendRequests[gfc_$a]()?"friend-requests":"faces";c||gfc_Mm("friend")};
gfc_7[gfc_].$s=function(a){this.d[gfc_q][gfc_D].sites=a.get("profileSites")[gfc_r]();this.d[gfc_q][gfc_D].friends=a.get("friends")[gfc_r]()};gfc_7[gfc_].Mp=function(){return this.uv};gfc_7[gfc_].X=function(){this.Gw.rebuild();this.Cn();gfc_e[gfc_Za].adjustHeight()};gfc_7[gfc_].ss=function(a){return a=gfc_S("span",{"class":"fc-cap-link-big"},gfc_S("a",{"class":"fc-cap-link-big"},this.e.MSG_OPTIONS),a.Dg())};
gfc_7[gfc_].rs=function(){var a=[];a[a[gfc_m]]=gfc_S("div",{"class":"goog-menuitem menuaction-settings"},this.e.MSG_SITE_SETTINGS);a[a[gfc_m]]=this.isSocialShareEnabled?gfc_S("div",{"class":"goog-menuitem menuaction-share"},this.e.MSG_MEMBERS_SHARE):gfc_S("div",{"class":"goog-menuitem menuaction-invite"},this.e.MSG_INVITE_FRIENDS);this.d[gfc_q].isViewerAdmin&&!this.Ib()&&(a[a[gfc_m]]=gfc_S("div",{"class":"goog-menuitem menuaction-manage"},this.e.MSG_MANAGE));a[a[gfc_m]]=gfc_S("div",{"class":"goog-menuitem menuaction-signout"},
this.hb.signOutPrompt||this.e.MSG_SIGN_OUT);a[a[gfc_m]]=gfc_S("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_m]]=gfc_S("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_S("span",{"class":"fc-small-menu-link"},this.e.MSG_ABOUT_FC));return a};
gfc_7[gfc_].ts=function(a){a[gfc_wb]();a=a[gfc_Sb].g()[gfc_8a];a[gfc_Zb]("menuaction-settings")?this.Ab():a[gfc_Zb]("menuaction-invite")?this.invite():a[gfc_Zb]("menuaction-share")?this.share():a[gfc_Zb]("menuaction-signout")?this.signout():a[gfc_Zb]("menuaction-manage")?this.dq():a[gfc_Zb]("menuaction-aboutfc")&&(a=gfc_g[gfc_3a](gfc_Tm()+"/friendconnect"),a[gfc_7b]())};gfc_7[gfc_].dq=function(){var a={},b=gfc_e[gfc_n][gfc_pb]().canvas;gfc_Mm("lightbox");gfc_e[gfc_n].requestNavigateTo(b,a);return gfc_d};
var gfc_Kn=function(a){for(var b={},c=0;c<a[gfc_m];++c)b[a[c]]=a[c];return b}("HEIGHT,BORDER_COLOR,CONTENT_BG_COLOR,CONTENT_HEADLINE_COLOR,CONTENT_LINK_COLOR,CONTENT_SECONDARY_TEXT_COLOR,CONTENT_SECONDARY_LINK_COLOR,CONTENT_TEXT_COLOR,ENDCAP_BG_COLOR,ENDCAP_LINK_COLOR,ENDCAP_TEXT_COLOR,FACE_SIZE,NUMBER_ROWS".split(","));
gfc_7[gfc_].s=function(){var a=gfc_Kn,b=[],c=0;this.f(a.HEIGHT);this.Gh()&&(b[c++]=this.j(".fc-thumbnail img {height:%spx;width:%spx}",this.f(a.FACE_SIZE)));b[c++]=this.j(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.qm);b[c++]=this.j(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.f(a.BORDER_COLOR));this.pf()&&(this.Pk("profile")?b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n":this.Jh()?b[c++]=".fc-topcap {height: 0px;}\n":b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n");this.Ib()?b[c++]=".fc-userpic-caption {margin-left: 59px;}\n":b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";this.Jh()?b[c++]=".fc-topcap-color {background-color: white;}\n":b[c++]=this.j(".fc-topcap-color {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));this.cl()?b[c++]=
".fc-botcap-short {background-color: white;}\n":b[c++]=this.j(".fc-botcap-short {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",this.f(a.ENDCAP_TEXT_COLOR));
b[c++]=this.j(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.f(a.ENDCAP_LINK_COLOR));b[c++]=this.j(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.f(a.CONTENT_BG_COLOR));b[c++]=this.j(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.f(a.CONTENT_LINK_COLOR));b[c++]=this.j(".fc-members,.fc-members-canvas {color:%s;}\n",this.f(a.CONTENT_TEXT_COLOR));b[c++]=this.j(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.f(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.j(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.f(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.j(".fc-sectitle {color: %s;}\n",
this.f(a.CONTENT_HEADLINE_COLOR));return gfc_7.i.s[gfc_A](this)+b[gfc_K]("\n")};gfc_M("goog.peoplesense.gadget.Members",gfc_7);gfc_M("goog.peoplesense.gadget.Members.start",gfc_7[gfc_C]);var gfc_Ln=function(a,b,c){gfc_h.Collection[gfc_A](this,a[gfc_hb](c,c+b),c,a[gfc_m]);this.mw=a;this.ea=b};gfc_Ln.inherits(gfc_h.Collection);gfc_Ln[gfc_].all=function(){return this.mw};gfc_Ln[gfc_].mb=function(){return this.ea};gfc_M("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_Ln[gfc_].all);
gfc_M("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_Ln[gfc_].mb);
