// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class RepositoryView {
        
        private Gtk.Notebook Notebook;
        
        private Gtk.Table table4;
        
        private Gtk.Entry CityEntry;
        
        private Gtk.Entry CountryEntry;
        
        private Gtk.Entry EmailEntry;
        
        private Gtk.Label label1;
        
        private Gtk.Label label14;
        
        private Gtk.Label label20;
        
        private Gtk.Label label21;
        
        private Gtk.Label label23;
        
        private Gtk.Label label24;
        
        private Gtk.Label label26;
        
        private Gtk.Label label27;
        
        private Gtk.Label label28;
        
        private Gtk.Label label29;
        
        private Gtk.Entry NameEntry;
        
        private Gtk.Entry PhoneNumberEntry;
        
        private Gtk.Entry PostCodeEntry;
        
        private Gtk.Entry StateEntry;
        
        private Gtk.Entry Street1Entry;
        
        private Gtk.Entry Street2Entry;
        
        private Gtk.Entry WebSiteEntry;
        
        private Gtk.Label label5;
        
        private Gedcom.UI.GTK.Widgets.NotesView NotesView;
        
        private Gtk.Label label7;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.RepositoryView
            Stetic.BinContainer.Attach(this);
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.Widgets.RepositoryView";
            // Container child Gedcom.UI.GTK.Widgets.RepositoryView.Gtk.Container+ContainerChild
            this.Notebook = new Gtk.Notebook();
            this.Notebook.CanFocus = true;
            this.Notebook.Name = "Notebook";
            this.Notebook.CurrentPage = 1;
            // Container child Notebook.Gtk.Notebook+NotebookChild
            this.table4 = new Gtk.Table(((uint)(10)), ((uint)(2)), false);
            this.table4.Name = "table4";
            this.table4.RowSpacing = ((uint)(6));
            this.table4.ColumnSpacing = ((uint)(12));
            this.table4.BorderWidth = ((uint)(6));
            // Container child table4.Gtk.Table+TableChild
            this.CityEntry = new Gtk.Entry();
            this.CityEntry.CanFocus = true;
            this.CityEntry.Name = "CityEntry";
            this.CityEntry.IsEditable = true;
            this.CityEntry.InvisibleChar = '●';
            this.table4.Add(this.CityEntry);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table4[this.CityEntry]));
            w1.TopAttach = ((uint)(3));
            w1.BottomAttach = ((uint)(4));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.CountryEntry = new Gtk.Entry();
            this.CountryEntry.CanFocus = true;
            this.CountryEntry.Name = "CountryEntry";
            this.CountryEntry.IsEditable = true;
            this.CountryEntry.InvisibleChar = '●';
            this.table4.Add(this.CountryEntry);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table4[this.CountryEntry]));
            w2.TopAttach = ((uint)(6));
            w2.BottomAttach = ((uint)(7));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.EmailEntry = new Gtk.Entry();
            this.EmailEntry.CanFocus = true;
            this.EmailEntry.Name = "EmailEntry";
            this.EmailEntry.IsEditable = true;
            this.EmailEntry.InvisibleChar = '●';
            this.table4.Add(this.EmailEntry);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table4[this.EmailEntry]));
            w3.TopAttach = ((uint)(8));
            w3.BottomAttach = ((uint)(9));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = "Name:";
            this.table4.Add(this.label1);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table4[this.label1]));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label14 = new Gtk.Label();
            this.label14.Name = "label14";
            this.label14.Xalign = 0F;
            this.label14.LabelProp = "Street 2:";
            this.table4.Add(this.label14);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table4[this.label14]));
            w5.TopAttach = ((uint)(2));
            w5.BottomAttach = ((uint)(3));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label20 = new Gtk.Label();
            this.label20.Name = "label20";
            this.label20.Xalign = 0F;
            this.label20.LabelProp = "Street 1:";
            this.table4.Add(this.label20);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table4[this.label20]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label21 = new Gtk.Label();
            this.label21.Name = "label21";
            this.label21.Xalign = 0F;
            this.label21.LabelProp = "Phone Number(s):";
            this.table4.Add(this.label21);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table4[this.label21]));
            w7.TopAttach = ((uint)(7));
            w7.BottomAttach = ((uint)(8));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label23 = new Gtk.Label();
            this.label23.Name = "label23";
            this.label23.Xalign = 0F;
            this.label23.LabelProp = "E-Mail(s):";
            this.table4.Add(this.label23);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table4[this.label23]));
            w8.TopAttach = ((uint)(8));
            w8.BottomAttach = ((uint)(9));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label24 = new Gtk.Label();
            this.label24.Name = "label24";
            this.label24.Xalign = 0F;
            this.label24.LabelProp = "Country:";
            this.table4.Add(this.label24);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table4[this.label24]));
            w9.TopAttach = ((uint)(6));
            w9.BottomAttach = ((uint)(7));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label26 = new Gtk.Label();
            this.label26.Name = "label26";
            this.label26.Xalign = 0F;
            this.label26.LabelProp = "Post / Zip Code:";
            this.table4.Add(this.label26);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table4[this.label26]));
            w10.TopAttach = ((uint)(5));
            w10.BottomAttach = ((uint)(6));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label27 = new Gtk.Label();
            this.label27.Name = "label27";
            this.label27.Xalign = 0F;
            this.label27.LabelProp = "City:";
            this.table4.Add(this.label27);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table4[this.label27]));
            w11.TopAttach = ((uint)(3));
            w11.BottomAttach = ((uint)(4));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label28 = new Gtk.Label();
            this.label28.Name = "label28";
            this.label28.Xalign = 0F;
            this.label28.LabelProp = "State / Province / County:";
            this.table4.Add(this.label28);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table4[this.label28]));
            w12.TopAttach = ((uint)(4));
            w12.BottomAttach = ((uint)(5));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label29 = new Gtk.Label();
            this.label29.Name = "label29";
            this.label29.Xalign = 0F;
            this.label29.LabelProp = "Web Site(s):";
            this.table4.Add(this.label29);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table4[this.label29]));
            w13.TopAttach = ((uint)(9));
            w13.BottomAttach = ((uint)(10));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.NameEntry = new Gtk.Entry();
            this.NameEntry.CanFocus = true;
            this.NameEntry.Name = "NameEntry";
            this.NameEntry.IsEditable = true;
            this.NameEntry.InvisibleChar = '●';
            this.table4.Add(this.NameEntry);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table4[this.NameEntry]));
            w14.LeftAttach = ((uint)(1));
            w14.RightAttach = ((uint)(2));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.PhoneNumberEntry = new Gtk.Entry();
            this.PhoneNumberEntry.CanFocus = true;
            this.PhoneNumberEntry.Name = "PhoneNumberEntry";
            this.PhoneNumberEntry.IsEditable = true;
            this.PhoneNumberEntry.InvisibleChar = '●';
            this.table4.Add(this.PhoneNumberEntry);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table4[this.PhoneNumberEntry]));
            w15.TopAttach = ((uint)(7));
            w15.BottomAttach = ((uint)(8));
            w15.LeftAttach = ((uint)(1));
            w15.RightAttach = ((uint)(2));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.PostCodeEntry = new Gtk.Entry();
            this.PostCodeEntry.CanFocus = true;
            this.PostCodeEntry.Name = "PostCodeEntry";
            this.PostCodeEntry.IsEditable = true;
            this.PostCodeEntry.InvisibleChar = '●';
            this.table4.Add(this.PostCodeEntry);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table4[this.PostCodeEntry]));
            w16.TopAttach = ((uint)(5));
            w16.BottomAttach = ((uint)(6));
            w16.LeftAttach = ((uint)(1));
            w16.RightAttach = ((uint)(2));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.StateEntry = new Gtk.Entry();
            this.StateEntry.CanFocus = true;
            this.StateEntry.Name = "StateEntry";
            this.StateEntry.IsEditable = true;
            this.StateEntry.InvisibleChar = '●';
            this.table4.Add(this.StateEntry);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table4[this.StateEntry]));
            w17.TopAttach = ((uint)(4));
            w17.BottomAttach = ((uint)(5));
            w17.LeftAttach = ((uint)(1));
            w17.RightAttach = ((uint)(2));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.Street1Entry = new Gtk.Entry();
            this.Street1Entry.CanFocus = true;
            this.Street1Entry.Name = "Street1Entry";
            this.Street1Entry.IsEditable = true;
            this.Street1Entry.InvisibleChar = '●';
            this.table4.Add(this.Street1Entry);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table4[this.Street1Entry]));
            w18.TopAttach = ((uint)(1));
            w18.BottomAttach = ((uint)(2));
            w18.LeftAttach = ((uint)(1));
            w18.RightAttach = ((uint)(2));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.Street2Entry = new Gtk.Entry();
            this.Street2Entry.CanFocus = true;
            this.Street2Entry.Name = "Street2Entry";
            this.Street2Entry.IsEditable = true;
            this.Street2Entry.InvisibleChar = '●';
            this.table4.Add(this.Street2Entry);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table4[this.Street2Entry]));
            w19.TopAttach = ((uint)(2));
            w19.BottomAttach = ((uint)(3));
            w19.LeftAttach = ((uint)(1));
            w19.RightAttach = ((uint)(2));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.WebSiteEntry = new Gtk.Entry();
            this.WebSiteEntry.CanFocus = true;
            this.WebSiteEntry.Name = "WebSiteEntry";
            this.WebSiteEntry.IsEditable = true;
            this.WebSiteEntry.InvisibleChar = '●';
            this.table4.Add(this.WebSiteEntry);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table4[this.WebSiteEntry]));
            w20.TopAttach = ((uint)(9));
            w20.BottomAttach = ((uint)(10));
            w20.LeftAttach = ((uint)(1));
            w20.RightAttach = ((uint)(2));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            this.Notebook.Add(this.table4);
            // Notebook tab
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = "Details";
            this.Notebook.SetTabLabel(this.table4, this.label5);
            this.label5.ShowAll();
            // Container child Notebook.Gtk.Notebook+NotebookChild
            this.NotesView = new Gedcom.UI.GTK.Widgets.NotesView();
            this.NotesView.Events = ((Gdk.EventMask)(256));
            this.NotesView.Name = "NotesView";
            this.NotesView.DataNotes = false;
            this.NotesView.ListOnly = false;
            this.NotesView.NoteOnly = false;
            this.Notebook.Add(this.NotesView);
            Gtk.Notebook.NotebookChild w22 = ((Gtk.Notebook.NotebookChild)(this.Notebook[this.NotesView]));
            w22.Position = 1;
            // Notebook tab
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = "Notes";
            this.Notebook.SetTabLabel(this.NotesView, this.label7);
            this.label7.ShowAll();
            this.Add(this.Notebook);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.Notebook.SwitchPage += new Gtk.SwitchPageHandler(this.OnNotebook_SwitchPage);
            this.NotesView.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnNotesView_ShowSourceCitation);
            this.NotesView.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnNotesView_SelectNewNote);
        }
    }
}
