// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class AddressView {
        
        private Gtk.Table table5;
        
        private Gtk.Entry CityEntry;
        
        private Gtk.Entry CountryEntry;
        
        private Gtk.HBox hbox5;
        
        private Gtk.Label label17;
        
        private Gtk.Entry AddressDateEntry;
        
        private Gtk.Button AddressSourceButton;
        
        private Gtk.Button AddressMoreButton;
        
        private Gtk.Button AddressScrapbookButton;
        
        private Gtk.HBox hbox6;
        
        private Gtk.Entry WebSiteEntry;
        
        private Gtk.Entry WebSite2Entry;
        
        private Gtk.Entry WebSite3Entry;
        
        private Gtk.HBox hbox7;
        
        private Gtk.ScrolledWindow scrolledwindow3;
        
        private Gtk.TreeView ResiTreeView;
        
        private Gtk.VBox vbox6;
        
        private Gtk.Button NewAddressButton;
        
        private Gtk.HBox hbox8;
        
        private Gtk.Entry PhoneNumberEntry;
        
        private Gtk.Entry PhoneNumber2Entry;
        
        private Gtk.Entry PhoneNumber3Entry;
        
        private Gtk.HBox hbox9;
        
        private Gtk.Entry EmailEntry;
        
        private Gtk.Entry Email2Entry;
        
        private Gtk.Entry Email3Entry;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Label label16;
        
        private Gtk.Label label20;
        
        private Gtk.Label label21;
        
        private Gtk.Label label23;
        
        private Gtk.Label label24;
        
        private Gtk.Label label26;
        
        private Gtk.Label label27;
        
        private Gtk.Label label28;
        
        private Gtk.Label label29;
        
        private Gtk.Entry PostCodeEntry;
        
        private Gtk.Entry StateEntry;
        
        private Gtk.Entry Street1Entry;
        
        private Gtk.Entry Street2Entry;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.AddressView
            Stetic.BinContainer.Attach(this);
            this.Name = "Gedcom.UI.GTK.Widgets.AddressView";
            // Container child Gedcom.UI.GTK.Widgets.AddressView.Gtk.Container+ContainerChild
            this.table5 = new Gtk.Table(((uint)(11)), ((uint)(4)), false);
            this.table5.Name = "table5";
            this.table5.RowSpacing = ((uint)(6));
            this.table5.ColumnSpacing = ((uint)(12));
            this.table5.BorderWidth = ((uint)(6));
            // Container child table5.Gtk.Table+TableChild
            this.CityEntry = new Gtk.Entry();
            this.CityEntry.CanFocus = true;
            this.CityEntry.Name = "CityEntry";
            this.CityEntry.IsEditable = true;
            this.CityEntry.InvisibleChar = '●';
            this.table5.Add(this.CityEntry);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table5[this.CityEntry]));
            w1.TopAttach = ((uint)(4));
            w1.BottomAttach = ((uint)(5));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.CountryEntry = new Gtk.Entry();
            this.CountryEntry.CanFocus = true;
            this.CountryEntry.Name = "CountryEntry";
            this.CountryEntry.IsEditable = true;
            this.CountryEntry.InvisibleChar = '●';
            this.table5.Add(this.CountryEntry);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table5[this.CountryEntry]));
            w2.TopAttach = ((uint)(5));
            w2.BottomAttach = ((uint)(6));
            w2.LeftAttach = ((uint)(3));
            w2.RightAttach = ((uint)(4));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.label17 = new Gtk.Label();
            this.label17.Name = "label17";
            this.label17.Xalign = 0F;
            this.label17.LabelProp = "Date:";
            this.hbox5.Add(this.label17);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox5[this.label17]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.AddressDateEntry = new Gtk.Entry();
            this.AddressDateEntry.CanFocus = true;
            this.AddressDateEntry.Name = "AddressDateEntry";
            this.AddressDateEntry.IsEditable = true;
            this.AddressDateEntry.InvisibleChar = '●';
            this.hbox5.Add(this.AddressDateEntry);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox5[this.AddressDateEntry]));
            w4.Position = 1;
            // Container child hbox5.Gtk.Box+BoxChild
            this.AddressSourceButton = new Gtk.Button();
            this.AddressSourceButton.CanFocus = true;
            this.AddressSourceButton.Name = "AddressSourceButton";
            this.AddressSourceButton.UseUnderline = true;
            // Container child AddressSourceButton.Gtk.Container+ContainerChild
            Gtk.Alignment w5 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w6 = new Gtk.HBox();
            w6.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w7 = new Gtk.Image();
            w7.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            w6.Add(w7);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w9 = new Gtk.Label();
            w6.Add(w9);
            w5.Add(w6);
            this.AddressSourceButton.Add(w5);
            this.hbox5.Add(this.AddressSourceButton);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox5[this.AddressSourceButton]));
            w13.Position = 2;
            w13.Expand = false;
            w13.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.AddressMoreButton = new Gtk.Button();
            this.AddressMoreButton.CanFocus = true;
            this.AddressMoreButton.Name = "AddressMoreButton";
            this.AddressMoreButton.UseUnderline = true;
            // Container child AddressMoreButton.Gtk.Container+ContainerChild
            Gtk.Alignment w14 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w15 = new Gtk.HBox();
            w15.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w16 = new Gtk.Image();
            w16.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-edit", Gtk.IconSize.Button, 20);
            w15.Add(w16);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w18 = new Gtk.Label();
            w18.LabelProp = "More";
            w18.UseUnderline = true;
            w15.Add(w18);
            w14.Add(w15);
            this.AddressMoreButton.Add(w14);
            this.hbox5.Add(this.AddressMoreButton);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox5[this.AddressMoreButton]));
            w22.Position = 3;
            w22.Expand = false;
            w22.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.AddressScrapbookButton = new Gtk.Button();
            this.AddressScrapbookButton.CanFocus = true;
            this.AddressScrapbookButton.Name = "AddressScrapbookButton";
            this.AddressScrapbookButton.UseUnderline = true;
            // Container child AddressScrapbookButton.Gtk.Container+ContainerChild
            Gtk.Alignment w23 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w24 = new Gtk.HBox();
            w24.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w25 = new Gtk.Image();
            w25.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-paste", Gtk.IconSize.Button, 20);
            w24.Add(w25);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w27 = new Gtk.Label();
            w27.LabelProp = "Scrapbook";
            w27.UseUnderline = true;
            w24.Add(w27);
            w23.Add(w24);
            this.AddressScrapbookButton.Add(w23);
            this.hbox5.Add(this.AddressScrapbookButton);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.hbox5[this.AddressScrapbookButton]));
            w31.Position = 4;
            w31.Expand = false;
            w31.Fill = false;
            this.table5.Add(this.hbox5);
            Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table5[this.hbox5]));
            w32.RightAttach = ((uint)(4));
            w32.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.hbox6 = new Gtk.HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.WebSiteEntry = new Gtk.Entry();
            this.WebSiteEntry.CanFocus = true;
            this.WebSiteEntry.Name = "WebSiteEntry";
            this.WebSiteEntry.IsEditable = true;
            this.WebSiteEntry.InvisibleChar = '●';
            this.hbox6.Add(this.WebSiteEntry);
            Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.hbox6[this.WebSiteEntry]));
            w33.Position = 0;
            // Container child hbox6.Gtk.Box+BoxChild
            this.WebSite2Entry = new Gtk.Entry();
            this.WebSite2Entry.CanFocus = true;
            this.WebSite2Entry.Name = "WebSite2Entry";
            this.WebSite2Entry.IsEditable = true;
            this.WebSite2Entry.InvisibleChar = '●';
            this.hbox6.Add(this.WebSite2Entry);
            Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox6[this.WebSite2Entry]));
            w34.Position = 1;
            // Container child hbox6.Gtk.Box+BoxChild
            this.WebSite3Entry = new Gtk.Entry();
            this.WebSite3Entry.CanFocus = true;
            this.WebSite3Entry.Name = "WebSite3Entry";
            this.WebSite3Entry.IsEditable = true;
            this.WebSite3Entry.InvisibleChar = '●';
            this.hbox6.Add(this.WebSite3Entry);
            Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.hbox6[this.WebSite3Entry]));
            w35.Position = 2;
            this.table5.Add(this.hbox6);
            Gtk.Table.TableChild w36 = ((Gtk.Table.TableChild)(this.table5[this.hbox6]));
            w36.TopAttach = ((uint)(8));
            w36.BottomAttach = ((uint)(9));
            w36.LeftAttach = ((uint)(1));
            w36.RightAttach = ((uint)(4));
            w36.XOptions = ((Gtk.AttachOptions)(4));
            w36.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.hbox7 = new Gtk.HBox();
            this.hbox7.Name = "hbox7";
            this.hbox7.Spacing = 6;
            // Container child hbox7.Gtk.Box+BoxChild
            this.scrolledwindow3 = new Gtk.ScrolledWindow();
            this.scrolledwindow3.CanFocus = true;
            this.scrolledwindow3.Name = "scrolledwindow3";
            this.scrolledwindow3.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow3.Gtk.Container+ContainerChild
            this.ResiTreeView = new Gtk.TreeView();
            this.ResiTreeView.CanFocus = true;
            this.ResiTreeView.Name = "ResiTreeView";
            this.ResiTreeView.RulesHint = true;
            this.scrolledwindow3.Add(this.ResiTreeView);
            this.hbox7.Add(this.scrolledwindow3);
            Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.hbox7[this.scrolledwindow3]));
            w38.Position = 0;
            // Container child hbox7.Gtk.Box+BoxChild
            this.vbox6 = new Gtk.VBox();
            this.vbox6.Name = "vbox6";
            this.vbox6.Spacing = 6;
            // Container child vbox6.Gtk.Box+BoxChild
            this.NewAddressButton = new Gtk.Button();
            this.NewAddressButton.CanFocus = true;
            this.NewAddressButton.Name = "NewAddressButton";
            this.NewAddressButton.UseStock = true;
            this.NewAddressButton.UseUnderline = true;
            this.NewAddressButton.Label = "gtk-new";
            this.vbox6.Add(this.NewAddressButton);
            Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(this.vbox6[this.NewAddressButton]));
            w39.Position = 0;
            w39.Expand = false;
            w39.Fill = false;
            this.hbox7.Add(this.vbox6);
            Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.hbox7[this.vbox6]));
            w40.Position = 1;
            w40.Expand = false;
            w40.Fill = false;
            this.table5.Add(this.hbox7);
            Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table5[this.hbox7]));
            w41.TopAttach = ((uint)(10));
            w41.BottomAttach = ((uint)(11));
            w41.LeftAttach = ((uint)(1));
            w41.RightAttach = ((uint)(4));
            // Container child table5.Gtk.Table+TableChild
            this.hbox8 = new Gtk.HBox();
            this.hbox8.Name = "hbox8";
            this.hbox8.Spacing = 6;
            // Container child hbox8.Gtk.Box+BoxChild
            this.PhoneNumberEntry = new Gtk.Entry();
            this.PhoneNumberEntry.CanFocus = true;
            this.PhoneNumberEntry.Name = "PhoneNumberEntry";
            this.PhoneNumberEntry.IsEditable = true;
            this.PhoneNumberEntry.InvisibleChar = '●';
            this.hbox8.Add(this.PhoneNumberEntry);
            Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.hbox8[this.PhoneNumberEntry]));
            w42.Position = 0;
            // Container child hbox8.Gtk.Box+BoxChild
            this.PhoneNumber2Entry = new Gtk.Entry();
            this.PhoneNumber2Entry.CanFocus = true;
            this.PhoneNumber2Entry.Name = "PhoneNumber2Entry";
            this.PhoneNumber2Entry.IsEditable = true;
            this.PhoneNumber2Entry.InvisibleChar = '●';
            this.hbox8.Add(this.PhoneNumber2Entry);
            Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(this.hbox8[this.PhoneNumber2Entry]));
            w43.Position = 1;
            // Container child hbox8.Gtk.Box+BoxChild
            this.PhoneNumber3Entry = new Gtk.Entry();
            this.PhoneNumber3Entry.CanFocus = true;
            this.PhoneNumber3Entry.Name = "PhoneNumber3Entry";
            this.PhoneNumber3Entry.IsEditable = true;
            this.PhoneNumber3Entry.InvisibleChar = '●';
            this.hbox8.Add(this.PhoneNumber3Entry);
            Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.hbox8[this.PhoneNumber3Entry]));
            w44.Position = 2;
            this.table5.Add(this.hbox8);
            Gtk.Table.TableChild w45 = ((Gtk.Table.TableChild)(this.table5[this.hbox8]));
            w45.TopAttach = ((uint)(6));
            w45.BottomAttach = ((uint)(7));
            w45.LeftAttach = ((uint)(1));
            w45.RightAttach = ((uint)(4));
            w45.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.hbox9 = new Gtk.HBox();
            this.hbox9.Name = "hbox9";
            this.hbox9.Spacing = 6;
            // Container child hbox9.Gtk.Box+BoxChild
            this.EmailEntry = new Gtk.Entry();
            this.EmailEntry.CanFocus = true;
            this.EmailEntry.Name = "EmailEntry";
            this.EmailEntry.IsEditable = true;
            this.EmailEntry.InvisibleChar = '●';
            this.hbox9.Add(this.EmailEntry);
            Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.hbox9[this.EmailEntry]));
            w46.Position = 0;
            // Container child hbox9.Gtk.Box+BoxChild
            this.Email2Entry = new Gtk.Entry();
            this.Email2Entry.CanFocus = true;
            this.Email2Entry.Name = "Email2Entry";
            this.Email2Entry.IsEditable = true;
            this.Email2Entry.InvisibleChar = '●';
            this.hbox9.Add(this.Email2Entry);
            Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.hbox9[this.Email2Entry]));
            w47.Position = 1;
            // Container child hbox9.Gtk.Box+BoxChild
            this.Email3Entry = new Gtk.Entry();
            this.Email3Entry.CanFocus = true;
            this.Email3Entry.Name = "Email3Entry";
            this.Email3Entry.IsEditable = true;
            this.Email3Entry.InvisibleChar = '●';
            this.hbox9.Add(this.Email3Entry);
            Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.hbox9[this.Email3Entry]));
            w48.Position = 2;
            this.table5.Add(this.hbox9);
            Gtk.Table.TableChild w49 = ((Gtk.Table.TableChild)(this.table5[this.hbox9]));
            w49.TopAttach = ((uint)(7));
            w49.BottomAttach = ((uint)(8));
            w49.LeftAttach = ((uint)(1));
            w49.RightAttach = ((uint)(4));
            w49.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.table5.Add(this.hseparator1);
            Gtk.Table.TableChild w50 = ((Gtk.Table.TableChild)(this.table5[this.hseparator1]));
            w50.TopAttach = ((uint)(9));
            w50.BottomAttach = ((uint)(10));
            w50.RightAttach = ((uint)(4));
            w50.XOptions = ((Gtk.AttachOptions)(4));
            w50.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.table5.Add(this.hseparator2);
            Gtk.Table.TableChild w51 = ((Gtk.Table.TableChild)(this.table5[this.hseparator2]));
            w51.TopAttach = ((uint)(1));
            w51.BottomAttach = ((uint)(2));
            w51.RightAttach = ((uint)(4));
            w51.XOptions = ((Gtk.AttachOptions)(4));
            w51.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label16 = new Gtk.Label();
            this.label16.Name = "label16";
            this.label16.Xalign = 0F;
            this.label16.LabelProp = "Street 2:";
            this.table5.Add(this.label16);
            Gtk.Table.TableChild w52 = ((Gtk.Table.TableChild)(this.table5[this.label16]));
            w52.TopAttach = ((uint)(3));
            w52.BottomAttach = ((uint)(4));
            w52.XOptions = ((Gtk.AttachOptions)(4));
            w52.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label20 = new Gtk.Label();
            this.label20.Name = "label20";
            this.label20.Xalign = 0F;
            this.label20.LabelProp = "Street 1:";
            this.table5.Add(this.label20);
            Gtk.Table.TableChild w53 = ((Gtk.Table.TableChild)(this.table5[this.label20]));
            w53.TopAttach = ((uint)(2));
            w53.BottomAttach = ((uint)(3));
            w53.XOptions = ((Gtk.AttachOptions)(4));
            w53.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label21 = new Gtk.Label();
            this.label21.Name = "label21";
            this.label21.Xalign = 0F;
            this.label21.LabelProp = "Phone Number(s):";
            this.table5.Add(this.label21);
            Gtk.Table.TableChild w54 = ((Gtk.Table.TableChild)(this.table5[this.label21]));
            w54.TopAttach = ((uint)(6));
            w54.BottomAttach = ((uint)(7));
            w54.XOptions = ((Gtk.AttachOptions)(4));
            w54.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label23 = new Gtk.Label();
            this.label23.Name = "label23";
            this.label23.Xalign = 0F;
            this.label23.LabelProp = "E-Mail(s):";
            this.table5.Add(this.label23);
            Gtk.Table.TableChild w55 = ((Gtk.Table.TableChild)(this.table5[this.label23]));
            w55.TopAttach = ((uint)(7));
            w55.BottomAttach = ((uint)(8));
            w55.XOptions = ((Gtk.AttachOptions)(4));
            w55.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label24 = new Gtk.Label();
            this.label24.Name = "label24";
            this.label24.Xalign = 1F;
            this.label24.LabelProp = "Country:";
            this.table5.Add(this.label24);
            Gtk.Table.TableChild w56 = ((Gtk.Table.TableChild)(this.table5[this.label24]));
            w56.TopAttach = ((uint)(5));
            w56.BottomAttach = ((uint)(6));
            w56.LeftAttach = ((uint)(2));
            w56.RightAttach = ((uint)(3));
            w56.XOptions = ((Gtk.AttachOptions)(4));
            w56.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label26 = new Gtk.Label();
            this.label26.Name = "label26";
            this.label26.Xalign = 0F;
            this.label26.LabelProp = "Post / Zip Code:";
            this.table5.Add(this.label26);
            Gtk.Table.TableChild w57 = ((Gtk.Table.TableChild)(this.table5[this.label26]));
            w57.TopAttach = ((uint)(5));
            w57.BottomAttach = ((uint)(6));
            w57.XOptions = ((Gtk.AttachOptions)(4));
            w57.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label27 = new Gtk.Label();
            this.label27.Name = "label27";
            this.label27.Xalign = 0F;
            this.label27.LabelProp = "City:";
            this.table5.Add(this.label27);
            Gtk.Table.TableChild w58 = ((Gtk.Table.TableChild)(this.table5[this.label27]));
            w58.TopAttach = ((uint)(4));
            w58.BottomAttach = ((uint)(5));
            w58.XOptions = ((Gtk.AttachOptions)(4));
            w58.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label28 = new Gtk.Label();
            this.label28.Name = "label28";
            this.label28.Xalign = 1F;
            this.label28.LabelProp = "State / Province / County:";
            this.table5.Add(this.label28);
            Gtk.Table.TableChild w59 = ((Gtk.Table.TableChild)(this.table5[this.label28]));
            w59.TopAttach = ((uint)(4));
            w59.BottomAttach = ((uint)(5));
            w59.LeftAttach = ((uint)(2));
            w59.RightAttach = ((uint)(3));
            w59.XOptions = ((Gtk.AttachOptions)(4));
            w59.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.label29 = new Gtk.Label();
            this.label29.Name = "label29";
            this.label29.Xalign = 0F;
            this.label29.LabelProp = "Web Site(s):";
            this.table5.Add(this.label29);
            Gtk.Table.TableChild w60 = ((Gtk.Table.TableChild)(this.table5[this.label29]));
            w60.TopAttach = ((uint)(8));
            w60.BottomAttach = ((uint)(9));
            w60.XOptions = ((Gtk.AttachOptions)(4));
            w60.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.PostCodeEntry = new Gtk.Entry();
            this.PostCodeEntry.CanFocus = true;
            this.PostCodeEntry.Name = "PostCodeEntry";
            this.PostCodeEntry.IsEditable = true;
            this.PostCodeEntry.InvisibleChar = '●';
            this.table5.Add(this.PostCodeEntry);
            Gtk.Table.TableChild w61 = ((Gtk.Table.TableChild)(this.table5[this.PostCodeEntry]));
            w61.TopAttach = ((uint)(5));
            w61.BottomAttach = ((uint)(6));
            w61.LeftAttach = ((uint)(1));
            w61.RightAttach = ((uint)(2));
            w61.XOptions = ((Gtk.AttachOptions)(4));
            w61.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.StateEntry = new Gtk.Entry();
            this.StateEntry.CanFocus = true;
            this.StateEntry.Name = "StateEntry";
            this.StateEntry.IsEditable = true;
            this.StateEntry.InvisibleChar = '●';
            this.table5.Add(this.StateEntry);
            Gtk.Table.TableChild w62 = ((Gtk.Table.TableChild)(this.table5[this.StateEntry]));
            w62.TopAttach = ((uint)(4));
            w62.BottomAttach = ((uint)(5));
            w62.LeftAttach = ((uint)(3));
            w62.RightAttach = ((uint)(4));
            w62.XOptions = ((Gtk.AttachOptions)(4));
            w62.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.Street1Entry = new Gtk.Entry();
            this.Street1Entry.CanFocus = true;
            this.Street1Entry.Name = "Street1Entry";
            this.Street1Entry.IsEditable = true;
            this.Street1Entry.InvisibleChar = '●';
            this.table5.Add(this.Street1Entry);
            Gtk.Table.TableChild w63 = ((Gtk.Table.TableChild)(this.table5[this.Street1Entry]));
            w63.TopAttach = ((uint)(2));
            w63.BottomAttach = ((uint)(3));
            w63.LeftAttach = ((uint)(1));
            w63.RightAttach = ((uint)(3));
            w63.XOptions = ((Gtk.AttachOptions)(4));
            w63.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.Street2Entry = new Gtk.Entry();
            this.Street2Entry.CanFocus = true;
            this.Street2Entry.Name = "Street2Entry";
            this.Street2Entry.IsEditable = true;
            this.Street2Entry.InvisibleChar = '●';
            this.table5.Add(this.Street2Entry);
            Gtk.Table.TableChild w64 = ((Gtk.Table.TableChild)(this.table5[this.Street2Entry]));
            w64.TopAttach = ((uint)(3));
            w64.BottomAttach = ((uint)(4));
            w64.LeftAttach = ((uint)(1));
            w64.RightAttach = ((uint)(3));
            w64.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table5);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.NewAddressButton.Clicked += new System.EventHandler(this.OnNewAddressButton_Clicked);
        }
    }
}
