// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class ScrapBookView {
        
        private Gtk.HBox hbox1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.ScrolledWindow RecordsScrolledWindow;
        
        private Gtk.TreeView RecordTreeView;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Button AddRecordButton;
        
        private Gtk.Button RemoveRecordButton;
        
        private Gtk.VSeparator vseparator1;
        
        private Gtk.Notebook DetailsNotebook;
        
        private Gtk.VBox vbox3;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label1;
        
        private Gtk.Entry TitleEntry;
        
        private Gtk.ScrolledWindow scrolledwindow2;
        
        private Gtk.TreeView FileTreeView;
        
        private Gtk.HButtonBox hbuttonbox3;
        
        private Gtk.Button AddFileButton;
        
        private Gtk.Button RemoveFileButton;
        
        private Gtk.Label DetailsLabel;
        
        private Gedcom.UI.GTK.Widgets.NotesView NotesView;
        
        private Gtk.Label label2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.ScrapBookView
            Stetic.BinContainer.Attach(this);
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.Widgets.ScrapBookView";
            // Container child Gedcom.UI.GTK.Widgets.ScrapBookView.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.RecordsScrolledWindow = new Gtk.ScrolledWindow();
            this.RecordsScrolledWindow.CanFocus = true;
            this.RecordsScrolledWindow.Name = "RecordsScrolledWindow";
            this.RecordsScrolledWindow.HscrollbarPolicy = ((Gtk.PolicyType)(2));
            this.RecordsScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child RecordsScrolledWindow.Gtk.Container+ContainerChild
            this.RecordTreeView = new Gtk.TreeView();
            this.RecordTreeView.CanFocus = true;
            this.RecordTreeView.Name = "RecordTreeView";
            this.RecordsScrolledWindow.Add(this.RecordTreeView);
            this.vbox2.Add(this.RecordsScrolledWindow);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.RecordsScrolledWindow]));
            w2.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            this.hbuttonbox2.Spacing = 6;
            this.hbuttonbox2.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.AddRecordButton = new Gtk.Button();
            this.AddRecordButton.CanFocus = true;
            this.AddRecordButton.Name = "AddRecordButton";
            this.AddRecordButton.UseStock = true;
            this.AddRecordButton.UseUnderline = true;
            this.AddRecordButton.Label = "gtk-add";
            this.hbuttonbox2.Add(this.AddRecordButton);
            Gtk.ButtonBox.ButtonBoxChild w3 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.AddRecordButton]));
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.RemoveRecordButton = new Gtk.Button();
            this.RemoveRecordButton.CanFocus = true;
            this.RemoveRecordButton.Name = "RemoveRecordButton";
            this.RemoveRecordButton.UseStock = true;
            this.RemoveRecordButton.UseUnderline = true;
            this.RemoveRecordButton.Label = "gtk-remove";
            this.hbuttonbox2.Add(this.RemoveRecordButton);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.RemoveRecordButton]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.vbox2.Add(this.hbuttonbox2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox2]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.hbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
            w6.Position = 0;
            w6.Expand = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vseparator1 = new Gtk.VSeparator();
            this.vseparator1.Name = "vseparator1";
            this.hbox1.Add(this.vseparator1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.DetailsNotebook = new Gtk.Notebook();
            this.DetailsNotebook.CanFocus = true;
            this.DetailsNotebook.Name = "DetailsNotebook";
            this.DetailsNotebook.CurrentPage = 1;
            // Container child DetailsNotebook.Gtk.Notebook+NotebookChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = "Title:";
            this.hbox2.Add(this.label1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox2[this.label1]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.TitleEntry = new Gtk.Entry();
            this.TitleEntry.CanFocus = true;
            this.TitleEntry.Name = "TitleEntry";
            this.TitleEntry.IsEditable = true;
            this.TitleEntry.InvisibleChar = '●';
            this.hbox2.Add(this.TitleEntry);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox2[this.TitleEntry]));
            w9.Position = 1;
            this.vbox3.Add(this.hbox2);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.scrolledwindow2 = new Gtk.ScrolledWindow();
            this.scrolledwindow2.CanFocus = true;
            this.scrolledwindow2.Name = "scrolledwindow2";
            this.scrolledwindow2.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow2.Gtk.Container+ContainerChild
            this.FileTreeView = new Gtk.TreeView();
            this.FileTreeView.CanFocus = true;
            this.FileTreeView.Name = "FileTreeView";
            this.scrolledwindow2.Add(this.FileTreeView);
            this.vbox3.Add(this.scrolledwindow2);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox3[this.scrolledwindow2]));
            w12.Position = 1;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbuttonbox3 = new Gtk.HButtonBox();
            this.hbuttonbox3.Name = "hbuttonbox3";
            this.hbuttonbox3.Spacing = 6;
            this.hbuttonbox3.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
            this.AddFileButton = new Gtk.Button();
            this.AddFileButton.CanFocus = true;
            this.AddFileButton.Name = "AddFileButton";
            this.AddFileButton.UseStock = true;
            this.AddFileButton.UseUnderline = true;
            this.AddFileButton.Label = "gtk-add";
            this.hbuttonbox3.Add(this.AddFileButton);
            Gtk.ButtonBox.ButtonBoxChild w13 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.AddFileButton]));
            w13.Expand = false;
            w13.Fill = false;
            // Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
            this.RemoveFileButton = new Gtk.Button();
            this.RemoveFileButton.CanFocus = true;
            this.RemoveFileButton.Name = "RemoveFileButton";
            this.RemoveFileButton.UseStock = true;
            this.RemoveFileButton.UseUnderline = true;
            this.RemoveFileButton.Label = "gtk-remove";
            this.hbuttonbox3.Add(this.RemoveFileButton);
            Gtk.ButtonBox.ButtonBoxChild w14 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.RemoveFileButton]));
            w14.Position = 1;
            w14.Expand = false;
            w14.Fill = false;
            this.vbox3.Add(this.hbuttonbox3);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbuttonbox3]));
            w15.Position = 2;
            w15.Expand = false;
            w15.Fill = false;
            this.DetailsNotebook.Add(this.vbox3);
            // Notebook tab
            this.DetailsLabel = new Gtk.Label();
            this.DetailsLabel.Name = "DetailsLabel";
            this.DetailsLabel.LabelProp = "Details";
            this.DetailsNotebook.SetTabLabel(this.vbox3, this.DetailsLabel);
            this.DetailsLabel.ShowAll();
            // Container child DetailsNotebook.Gtk.Notebook+NotebookChild
            this.NotesView = new Gedcom.UI.GTK.Widgets.NotesView();
            this.NotesView.Events = ((Gdk.EventMask)(256));
            this.NotesView.Name = "NotesView";
            this.NotesView.DataNotes = false;
            this.NotesView.ListOnly = false;
            this.NotesView.NoteOnly = false;
            this.DetailsNotebook.Add(this.NotesView);
            Gtk.Notebook.NotebookChild w17 = ((Gtk.Notebook.NotebookChild)(this.DetailsNotebook[this.NotesView]));
            w17.Position = 1;
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = "Notes";
            this.DetailsNotebook.SetTabLabel(this.NotesView, this.label2);
            this.label2.ShowAll();
            this.hbox1.Add(this.DetailsNotebook);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox1[this.DetailsNotebook]));
            w18.Position = 2;
            this.Add(this.hbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.AddRecordButton.Clicked += new System.EventHandler(this.OnAddRecordButton_Clicked);
            this.RemoveRecordButton.Clicked += new System.EventHandler(this.OnRemoveRecordButton_Clicked);
            this.FileTreeView.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnFileTreeView_ButtonPressEvent);
            this.AddFileButton.Clicked += new System.EventHandler(this.OnAddFileButton_Clicked);
            this.RemoveFileButton.Clicked += new System.EventHandler(this.OnRemoveFileButton_Clicked);
            this.NotesView.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnNotesView_ShowSourceCitation);
            this.NotesView.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnNotesView_SelectNewNote);
        }
    }
}
