// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class FamilyView {
        
        private Gtk.Table table1;
        
        private Gtk.HBox hbox7;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView ChildrenTreeView;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Button AddChildButton;
        
        private Gtk.Button NewChildButton;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.HSeparator hseparator3;
        
        private Gedcom.UI.GTK.Widgets.SpouseView HusbandSpouseView;
        
        private Gedcom.UI.GTK.Widgets.MarriageView MarriageView;
        
        private Gtk.VSeparator vseparator2;
        
        private Gedcom.UI.GTK.Widgets.SpouseView WifeSpouseView;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.FamilyView
            Stetic.BinContainer.Attach(this);
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.Widgets.FamilyView";
            // Container child Gedcom.UI.GTK.Widgets.FamilyView.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(5)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(12));
            this.table1.BorderWidth = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.hbox7 = new Gtk.HBox();
            this.hbox7.Name = "hbox7";
            this.hbox7.Spacing = 6;
            // Container child hbox7.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.ChildrenTreeView = new Gtk.TreeView();
            this.ChildrenTreeView.CanFocus = true;
            this.ChildrenTreeView.Name = "ChildrenTreeView";
            this.ChildrenTreeView.RulesHint = true;
            this.scrolledwindow1.Add(this.ChildrenTreeView);
            this.hbox7.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox7[this.scrolledwindow1]));
            w2.Position = 0;
            // Container child hbox7.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.AddChildButton = new Gtk.Button();
            this.AddChildButton.CanFocus = true;
            this.AddChildButton.Name = "AddChildButton";
            this.AddChildButton.UseStock = true;
            this.AddChildButton.UseUnderline = true;
            this.AddChildButton.Label = "gtk-add";
            this.vbox2.Add(this.AddChildButton);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.AddChildButton]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.NewChildButton = new Gtk.Button();
            this.NewChildButton.CanFocus = true;
            this.NewChildButton.Name = "NewChildButton";
            this.NewChildButton.UseStock = true;
            this.NewChildButton.UseUnderline = true;
            this.NewChildButton.Label = "gtk-new";
            this.vbox2.Add(this.NewChildButton);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.NewChildButton]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.hbox7.Add(this.vbox2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox7[this.vbox2]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.table1.Add(this.hbox7);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.hbox7]));
            w6.TopAttach = ((uint)(4));
            w6.BottomAttach = ((uint)(5));
            w6.RightAttach = ((uint)(5));
            // Container child table1.Gtk.Table+TableChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.table1.Add(this.hseparator2);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.hseparator2]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.RightAttach = ((uint)(5));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hseparator3 = new Gtk.HSeparator();
            this.hseparator3.Name = "hseparator3";
            this.table1.Add(this.hseparator3);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.hseparator3]));
            w8.TopAttach = ((uint)(3));
            w8.BottomAttach = ((uint)(4));
            w8.RightAttach = ((uint)(5));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandSpouseView = new Gedcom.UI.GTK.Widgets.SpouseView();
            this.HusbandSpouseView.Events = ((Gdk.EventMask)(256));
            this.HusbandSpouseView.Name = "HusbandSpouseView";
            this.HusbandSpouseView.NameLabel = "Husband:";
            this.table1.Add(this.HusbandSpouseView);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.HusbandSpouseView]));
            w9.RightAttach = ((uint)(3));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.MarriageView = new Gedcom.UI.GTK.Widgets.MarriageView();
            this.MarriageView.Events = ((Gdk.EventMask)(256));
            this.MarriageView.Name = "MarriageView";
            this.table1.Add(this.MarriageView);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.MarriageView]));
            w10.TopAttach = ((uint)(2));
            w10.BottomAttach = ((uint)(3));
            w10.RightAttach = ((uint)(5));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.vseparator2 = new Gtk.VSeparator();
            this.vseparator2.Name = "vseparator2";
            this.table1.Add(this.vseparator2);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.vseparator2]));
            w11.LeftAttach = ((uint)(3));
            w11.RightAttach = ((uint)(4));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.WifeSpouseView = new Gedcom.UI.GTK.Widgets.SpouseView();
            this.WifeSpouseView.Events = ((Gdk.EventMask)(256));
            this.WifeSpouseView.Name = "WifeSpouseView";
            this.WifeSpouseView.NameLabel = "Wife:";
            this.table1.Add(this.WifeSpouseView);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.WifeSpouseView]));
            w12.LeftAttach = ((uint)(4));
            w12.RightAttach = ((uint)(5));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.ChildrenTreeView.RowActivated += new Gtk.RowActivatedHandler(this.OnChildrenTreeView_RowActivated);
            this.ChildrenTreeView.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnChildrenTreeView_ButtonPressEvent);
            this.AddChildButton.Clicked += new System.EventHandler(this.OnAddChildButton_Clicked);
            this.NewChildButton.Clicked += new System.EventHandler(this.OnNewChildButton_Clicked);
        }
    }
}
