// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class NotesView {
        
        private Gtk.VBox vbox3;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TextView NotesTextView;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ScrolledWindow scrolledwindow7;
        
        private Gtk.TreeView NotesTreeView;
        
        private Gtk.VButtonBox vbuttonbox2;
        
        private Gtk.Button AddNoteButton;
        
        private Gtk.Button NewNoteButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.NotesView
            Stetic.BinContainer.Attach(this);
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.Widgets.NotesView";
            // Container child Gedcom.UI.GTK.Widgets.NotesView.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            this.vbox3.BorderWidth = ((uint)(6));
            // Container child vbox3.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.NotesTextView = new Gtk.TextView();
            this.NotesTextView.CanFocus = true;
            this.NotesTextView.Name = "NotesTextView";
            this.scrolledwindow1.Add(this.NotesTextView);
            this.vbox3.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox3[this.scrolledwindow1]));
            w2.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.scrolledwindow7 = new Gtk.ScrolledWindow();
            this.scrolledwindow7.CanFocus = true;
            this.scrolledwindow7.Name = "scrolledwindow7";
            this.scrolledwindow7.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow7.Gtk.Container+ContainerChild
            this.NotesTreeView = new Gtk.TreeView();
            this.NotesTreeView.CanFocus = true;
            this.NotesTreeView.Name = "NotesTreeView";
            this.scrolledwindow7.Add(this.NotesTreeView);
            this.hbox1.Add(this.scrolledwindow7);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.scrolledwindow7]));
            w4.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbuttonbox2 = new Gtk.VButtonBox();
            this.vbuttonbox2.Name = "vbuttonbox2";
            this.vbuttonbox2.Spacing = 6;
            this.vbuttonbox2.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.AddNoteButton = new Gtk.Button();
            this.AddNoteButton.CanFocus = true;
            this.AddNoteButton.Name = "AddNoteButton";
            this.AddNoteButton.UseStock = true;
            this.AddNoteButton.UseUnderline = true;
            this.AddNoteButton.Label = "gtk-add";
            this.vbuttonbox2.Add(this.AddNoteButton);
            Gtk.ButtonBox.ButtonBoxChild w5 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.AddNoteButton]));
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.NewNoteButton = new Gtk.Button();
            this.NewNoteButton.CanFocus = true;
            this.NewNoteButton.Name = "NewNoteButton";
            this.NewNoteButton.UseStock = true;
            this.NewNoteButton.UseUnderline = true;
            this.NewNoteButton.Label = "gtk-new";
            this.vbuttonbox2.Add(this.NewNoteButton);
            Gtk.ButtonBox.ButtonBoxChild w6 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.NewNoteButton]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            this.hbox1.Add(this.vbuttonbox2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox2]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            this.vbox3.Add(this.hbox1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
            w8.Position = 1;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.NotesTreeView.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnNotesTreeView_ButtonPressEvent);
            this.AddNoteButton.Clicked += new System.EventHandler(this.OnAddNoteButton_Clicked);
            this.NewNoteButton.Clicked += new System.EventHandler(this.OnNewNoteButton_Clicked);
        }
    }
}
