// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class DuplicateIndividualView {
        
        private Gtk.Table table1;
        
        private Gtk.HBox hbox8;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label ParentsLabel;
        
        private Gtk.Entry HusbandBornInEntry;
        
        private Gtk.Entry HusbandDateBornEntry;
        
        private Gtk.Button HusbandDateBornSourceButton;
        
        private Gtk.Image image439;
        
        private Gtk.Entry HusbandDateDiedEntry;
        
        private Gtk.Button HusbandDateDiedSourceButton;
        
        private Gtk.Image image440;
        
        private Gtk.Entry HusbandDiedInEntry;
        
        private Gtk.Entry HusbandNameEntry;
        
        private Gtk.Button HusbandNameSourceButton;
        
        private Gtk.Image image438;
        
        private Gtk.Label label10;
        
        private Gtk.Label label12;
        
        private Gtk.Label label18;
        
        private Gtk.Label label19;
        
        private Gtk.Button NameButton;
        
        private Gtk.Label SpouseNameLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.DuplicateIndividualView
            Stetic.BinContainer.Attach(this);
            this.Name = "Gedcom.UI.GTK.Widgets.DuplicateIndividualView";
            // Container child Gedcom.UI.GTK.Widgets.DuplicateIndividualView.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(6)), ((uint)(3)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(12));
            this.table1.BorderWidth = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.hbox8 = new Gtk.HBox();
            this.hbox8.Name = "hbox8";
            this.hbox8.Spacing = 6;
            // Container child hbox8.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.ParentsLabel = new Gtk.Label();
            this.ParentsLabel.Name = "ParentsLabel";
            this.ParentsLabel.LabelProp = "Parents";
            this.hbox1.Add(this.ParentsLabel);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.ParentsLabel]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            this.hbox8.Add(this.hbox1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox8[this.hbox1]));
            w2.Position = 0;
            this.table1.Add(this.hbox8);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.hbox8]));
            w3.RightAttach = ((uint)(3));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandBornInEntry = new Gtk.Entry();
            this.HusbandBornInEntry.CanFocus = true;
            this.HusbandBornInEntry.Name = "HusbandBornInEntry";
            this.HusbandBornInEntry.IsEditable = false;
            this.HusbandBornInEntry.InvisibleChar = '●';
            this.table1.Add(this.HusbandBornInEntry);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.HusbandBornInEntry]));
            w4.TopAttach = ((uint)(3));
            w4.BottomAttach = ((uint)(4));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandDateBornEntry = new Gtk.Entry();
            this.HusbandDateBornEntry.CanFocus = true;
            this.HusbandDateBornEntry.Name = "HusbandDateBornEntry";
            this.HusbandDateBornEntry.IsEditable = false;
            this.HusbandDateBornEntry.InvisibleChar = '●';
            this.table1.Add(this.HusbandDateBornEntry);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.HusbandDateBornEntry]));
            w5.TopAttach = ((uint)(2));
            w5.BottomAttach = ((uint)(3));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandDateBornSourceButton = new Gtk.Button();
            this.HusbandDateBornSourceButton.CanFocus = true;
            this.HusbandDateBornSourceButton.Name = "HusbandDateBornSourceButton";
            // Container child HusbandDateBornSourceButton.Gtk.Container+ContainerChild
            this.image439 = new Gtk.Image();
            this.image439.Name = "image439";
            this.image439.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            this.HusbandDateBornSourceButton.Add(this.image439);
            this.HusbandDateBornSourceButton.Label = null;
            this.table1.Add(this.HusbandDateBornSourceButton);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.HusbandDateBornSourceButton]));
            w7.TopAttach = ((uint)(2));
            w7.BottomAttach = ((uint)(3));
            w7.LeftAttach = ((uint)(2));
            w7.RightAttach = ((uint)(3));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandDateDiedEntry = new Gtk.Entry();
            this.HusbandDateDiedEntry.CanFocus = true;
            this.HusbandDateDiedEntry.Name = "HusbandDateDiedEntry";
            this.HusbandDateDiedEntry.IsEditable = false;
            this.HusbandDateDiedEntry.InvisibleChar = '●';
            this.table1.Add(this.HusbandDateDiedEntry);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.HusbandDateDiedEntry]));
            w8.TopAttach = ((uint)(4));
            w8.BottomAttach = ((uint)(5));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandDateDiedSourceButton = new Gtk.Button();
            this.HusbandDateDiedSourceButton.CanFocus = true;
            this.HusbandDateDiedSourceButton.Name = "HusbandDateDiedSourceButton";
            // Container child HusbandDateDiedSourceButton.Gtk.Container+ContainerChild
            this.image440 = new Gtk.Image();
            this.image440.Name = "image440";
            this.image440.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            this.HusbandDateDiedSourceButton.Add(this.image440);
            this.HusbandDateDiedSourceButton.Label = null;
            this.table1.Add(this.HusbandDateDiedSourceButton);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.HusbandDateDiedSourceButton]));
            w10.TopAttach = ((uint)(4));
            w10.BottomAttach = ((uint)(5));
            w10.LeftAttach = ((uint)(2));
            w10.RightAttach = ((uint)(3));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandDiedInEntry = new Gtk.Entry();
            this.HusbandDiedInEntry.CanFocus = true;
            this.HusbandDiedInEntry.Name = "HusbandDiedInEntry";
            this.HusbandDiedInEntry.IsEditable = false;
            this.HusbandDiedInEntry.InvisibleChar = '●';
            this.table1.Add(this.HusbandDiedInEntry);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.HusbandDiedInEntry]));
            w11.TopAttach = ((uint)(5));
            w11.BottomAttach = ((uint)(6));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandNameEntry = new Gtk.Entry();
            this.HusbandNameEntry.CanFocus = true;
            this.HusbandNameEntry.Name = "HusbandNameEntry";
            this.HusbandNameEntry.IsEditable = false;
            this.HusbandNameEntry.InvisibleChar = '●';
            this.table1.Add(this.HusbandNameEntry);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.HusbandNameEntry]));
            w12.TopAttach = ((uint)(1));
            w12.BottomAttach = ((uint)(2));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(2));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandNameSourceButton = new Gtk.Button();
            this.HusbandNameSourceButton.CanFocus = true;
            this.HusbandNameSourceButton.Name = "HusbandNameSourceButton";
            // Container child HusbandNameSourceButton.Gtk.Container+ContainerChild
            this.image438 = new Gtk.Image();
            this.image438.Name = "image438";
            this.image438.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            this.HusbandNameSourceButton.Add(this.image438);
            this.HusbandNameSourceButton.Label = null;
            this.table1.Add(this.HusbandNameSourceButton);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.HusbandNameSourceButton]));
            w14.TopAttach = ((uint)(1));
            w14.BottomAttach = ((uint)(2));
            w14.LeftAttach = ((uint)(2));
            w14.RightAttach = ((uint)(3));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.Xalign = 1F;
            this.label10.LabelProp = "in:";
            this.table1.Add(this.label10);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.label10]));
            w15.TopAttach = ((uint)(5));
            w15.BottomAttach = ((uint)(6));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.Xalign = 1F;
            this.label12.LabelProp = "in:";
            this.table1.Add(this.label12);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.label12]));
            w16.TopAttach = ((uint)(3));
            w16.BottomAttach = ((uint)(4));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label18 = new Gtk.Label();
            this.label18.Name = "label18";
            this.label18.Xalign = 1F;
            this.label18.LabelProp = "Born:";
            this.table1.Add(this.label18);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table1[this.label18]));
            w17.TopAttach = ((uint)(2));
            w17.BottomAttach = ((uint)(3));
            w17.XOptions = ((Gtk.AttachOptions)(4));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label19 = new Gtk.Label();
            this.label19.Name = "label19";
            this.label19.Xalign = 1F;
            this.label19.LabelProp = "Died:";
            this.table1.Add(this.label19);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table1[this.label19]));
            w18.TopAttach = ((uint)(4));
            w18.BottomAttach = ((uint)(5));
            w18.XOptions = ((Gtk.AttachOptions)(4));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.NameButton = new Gtk.Button();
            this.NameButton.CanFocus = true;
            this.NameButton.Name = "NameButton";
            // Container child NameButton.Gtk.Container+ContainerChild
            this.SpouseNameLabel = new Gtk.Label();
            this.SpouseNameLabel.Name = "SpouseNameLabel";
            this.SpouseNameLabel.Xalign = 1F;
            this.SpouseNameLabel.LabelProp = "Name:";
            this.NameButton.Add(this.SpouseNameLabel);
            this.NameButton.Label = null;
            this.table1.Add(this.NameButton);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table1[this.NameButton]));
            w20.TopAttach = ((uint)(1));
            w20.BottomAttach = ((uint)(2));
            w20.XOptions = ((Gtk.AttachOptions)(4));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
