// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class DuplicateView {
        
        private Gtk.VPaned vpaned1;
        
        private Gedcom.UI.GTK.Widgets.IndividualList DuplicateList;
        
        private Gtk.VBox DetailsBox;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label DuplicatesLabel;
        
        private Gtk.Button MergeButton;
        
        private Gtk.HButtonBox hbuttonbox4;
        
        private Gtk.Button BackButton;
        
        private Gtk.Button ForwardButton;
        
        private Gtk.HBox hbox5;
        
        private Gedcom.UI.GTK.Widgets.DuplicateIndividualView PersonADuplicateView;
        
        private Gedcom.UI.GTK.Widgets.DuplicateIndividualView PersonBDuplicateView;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.DuplicateView
            Stetic.BinContainer.Attach(this);
            this.Name = "Gedcom.UI.GTK.Widgets.DuplicateView";
            // Container child Gedcom.UI.GTK.Widgets.DuplicateView.Gtk.Container+ContainerChild
            this.vpaned1 = new Gtk.VPaned();
            this.vpaned1.CanFocus = true;
            this.vpaned1.Name = "vpaned1";
            this.vpaned1.Position = 225;
            this.vpaned1.BorderWidth = ((uint)(6));
            // Container child vpaned1.Gtk.Paned+PanedChild
            this.DuplicateList = new Gedcom.UI.GTK.Widgets.IndividualList();
            this.DuplicateList.Events = ((Gdk.EventMask)(256));
            this.DuplicateList.Name = "DuplicateList";
            this.vpaned1.Add(this.DuplicateList);
            Gtk.Paned.PanedChild w1 = ((Gtk.Paned.PanedChild)(this.vpaned1[this.DuplicateList]));
            w1.Resize = false;
            // Container child vpaned1.Gtk.Paned+PanedChild
            this.DetailsBox = new Gtk.VBox();
            this.DetailsBox.Sensitive = false;
            this.DetailsBox.Name = "DetailsBox";
            this.DetailsBox.Spacing = 6;
            // Container child DetailsBox.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.DuplicatesLabel = new Gtk.Label();
            this.DuplicatesLabel.Name = "DuplicatesLabel";
            this.DuplicatesLabel.LabelProp = "Potential Duplicate 1 of 1";
            this.hbox3.Add(this.DuplicatesLabel);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.DuplicatesLabel]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.MergeButton = new Gtk.Button();
            this.MergeButton.CanFocus = true;
            this.MergeButton.Name = "MergeButton";
            this.MergeButton.UseUnderline = true;
            // Container child MergeButton.Gtk.Container+ContainerChild
            Gtk.Alignment w3 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w4 = new Gtk.HBox();
            w4.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w5 = new Gtk.Image();
            w5.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-convert", Gtk.IconSize.Button, 20);
            w4.Add(w5);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w7 = new Gtk.Label();
            w7.LabelProp = "Merge";
            w7.UseUnderline = true;
            w4.Add(w7);
            w3.Add(w4);
            this.MergeButton.Add(w3);
            this.hbox3.Add(this.MergeButton);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox3[this.MergeButton]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.hbuttonbox4 = new Gtk.HButtonBox();
            this.hbuttonbox4.Name = "hbuttonbox4";
            this.hbuttonbox4.Spacing = 6;
            this.hbuttonbox4.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
            this.BackButton = new Gtk.Button();
            this.BackButton.CanFocus = true;
            this.BackButton.Name = "BackButton";
            this.BackButton.UseStock = true;
            this.BackButton.UseUnderline = true;
            this.BackButton.Label = "gtk-go-back";
            this.hbuttonbox4.Add(this.BackButton);
            Gtk.ButtonBox.ButtonBoxChild w12 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.BackButton]));
            w12.Expand = false;
            w12.Fill = false;
            // Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
            this.ForwardButton = new Gtk.Button();
            this.ForwardButton.CanFocus = true;
            this.ForwardButton.Name = "ForwardButton";
            this.ForwardButton.UseStock = true;
            this.ForwardButton.UseUnderline = true;
            this.ForwardButton.Label = "gtk-go-forward";
            this.hbuttonbox4.Add(this.ForwardButton);
            Gtk.ButtonBox.ButtonBoxChild w13 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.ForwardButton]));
            w13.Position = 1;
            w13.Expand = false;
            w13.Fill = false;
            this.hbox3.Add(this.hbuttonbox4);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox3[this.hbuttonbox4]));
            w14.Position = 2;
            this.DetailsBox.Add(this.hbox3);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.DetailsBox[this.hbox3]));
            w15.Position = 0;
            w15.Fill = false;
            // Container child DetailsBox.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.PersonADuplicateView = new Gedcom.UI.GTK.Widgets.DuplicateIndividualView();
            this.PersonADuplicateView.Events = ((Gdk.EventMask)(256));
            this.PersonADuplicateView.Name = "PersonADuplicateView";
            this.hbox5.Add(this.PersonADuplicateView);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox5[this.PersonADuplicateView]));
            w16.Position = 0;
            // Container child hbox5.Gtk.Box+BoxChild
            this.PersonBDuplicateView = new Gedcom.UI.GTK.Widgets.DuplicateIndividualView();
            this.PersonBDuplicateView.Events = ((Gdk.EventMask)(256));
            this.PersonBDuplicateView.Name = "PersonBDuplicateView";
            this.hbox5.Add(this.PersonBDuplicateView);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox5[this.PersonBDuplicateView]));
            w17.Position = 1;
            this.DetailsBox.Add(this.hbox5);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.DetailsBox[this.hbox5]));
            w18.Position = 1;
            this.vpaned1.Add(this.DetailsBox);
            this.Add(this.vpaned1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.DuplicateList.RecordChanged += new System.EventHandler(this.OnDuplicateList_RecordChanged);
            this.MergeButton.Clicked += new System.EventHandler(this.OnMergeButton_Clicked);
            this.BackButton.Clicked += new System.EventHandler(this.OnBackButton_Clicked);
            this.ForwardButton.Clicked += new System.EventHandler(this.OnForwardButton_Clicked);
        }
    }
}
