// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class SubmitterView {
        
        private Gtk.Notebook notebook1;
        
        private Gtk.Table table1;
        
        private Gedcom.UI.GTK.Widgets.AddressView AddressView;
        
        private Gtk.Label label1;
        
        private Gtk.Entry NameEntry;
        
        private Gtk.Label label3;
        
        private Gedcom.UI.GTK.Widgets.ScrapBookView ScrapBookView;
        
        private Gtk.Label label4;
        
        private Gedcom.UI.GTK.Widgets.NotesView NotesView;
        
        private Gtk.Label label2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.SubmitterView
            Stetic.BinContainer.Attach(this);
            this.Name = "Gedcom.UI.GTK.Widgets.SubmitterView";
            // Container child Gedcom.UI.GTK.Widgets.SubmitterView.Gtk.Container+ContainerChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 2;
            this.notebook1.BorderWidth = ((uint)(6));
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.table1 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.AddressView = new Gedcom.UI.GTK.Widgets.AddressView();
            this.AddressView.Events = ((Gdk.EventMask)(256));
            this.AddressView.Name = "AddressView";
            this.table1.Add(this.AddressView);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.AddressView]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.RightAttach = ((uint)(2));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = "Name:";
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.NameEntry = new Gtk.Entry();
            this.NameEntry.CanFocus = true;
            this.NameEntry.Name = "NameEntry";
            this.NameEntry.IsEditable = true;
            this.NameEntry.InvisibleChar = '●';
            this.table1.Add(this.NameEntry);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.NameEntry]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            this.notebook1.Add(this.table1);
            // Notebook tab
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = "Details";
            this.notebook1.SetTabLabel(this.table1, this.label3);
            this.label3.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.ScrapBookView = new Gedcom.UI.GTK.Widgets.ScrapBookView();
            this.ScrapBookView.Events = ((Gdk.EventMask)(256));
            this.ScrapBookView.Name = "ScrapBookView";
            this.ScrapBookView.ShowRecordList = false;
            this.ScrapBookView.ShowFileList = false;
            this.notebook1.Add(this.ScrapBookView);
            Gtk.Notebook.NotebookChild w5 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.ScrapBookView]));
            w5.Position = 1;
            // Notebook tab
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = "Scrapbook";
            this.notebook1.SetTabLabel(this.ScrapBookView, this.label4);
            this.label4.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.NotesView = new Gedcom.UI.GTK.Widgets.NotesView();
            this.NotesView.Events = ((Gdk.EventMask)(256));
            this.NotesView.Name = "NotesView";
            this.NotesView.DataNotes = false;
            this.NotesView.ListOnly = false;
            this.NotesView.NoteOnly = false;
            this.notebook1.Add(this.NotesView);
            Gtk.Notebook.NotebookChild w6 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.NotesView]));
            w6.Position = 2;
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = "Notes";
            this.notebook1.SetTabLabel(this.NotesView, this.label2);
            this.label2.ShowAll();
            this.Add(this.notebook1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.ScrapBookView.FileSelected += new System.EventHandler(this.OnScrapBookView_FileSelected);
            this.ScrapBookView.FileDeSelected += new System.EventHandler(this.OnScrapBookView_FileDeSelected);
            this.ScrapBookView.OpenFile += new System.EventHandler<Gedcom.UI.Common.MultimediaFileArgs>(this.OnScrapBookView_OpenFile);
            this.ScrapBookView.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnScrapBookView_ShowSourceCitation);
            this.ScrapBookView.AddFile += new System.EventHandler<Gedcom.UI.Common.MultimediaFileArgs>(this.OnScrapBookView_AddFile);
            this.ScrapBookView.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnScrapBookView_SelectNewNote);
            this.NotesView.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnNotesViewShow_SourceCitation);
            this.NotesView.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnNotesView_SelectNewNote);
        }
    }
}
