// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class IndividualListComboBox {
        
        private Gtk.ComboBox Combo;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.IndividualListComboBox
            Stetic.BinContainer.Attach(this);
            this.Name = "Gedcom.UI.GTK.Widgets.IndividualListComboBox";
            // Container child Gedcom.UI.GTK.Widgets.IndividualListComboBox.Gtk.Container+ContainerChild
            this.Combo = Gtk.ComboBox.NewText();
            this.Combo.AppendText("NoIndividualText");
            this.Combo.Name = "Combo";
            this.Combo.Active = 0;
            this.Add(this.Combo);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.Combo.Changed += new System.EventHandler(this.OnCombo_Changed);
        }
    }
}
