// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class SpouseView {
        
        private Gtk.Table table1;
        
        private Gtk.HBox hbox8;
        
        private Gtk.Button RemoveHusbandButton;
        
        private Gtk.Image image413;
        
        private Gtk.Button AddHusbandButton;
        
        private Gtk.Image image414;
        
        private Gtk.Button DeleteButton;
        
        private Gtk.Image image415;
        
        private Gtk.HBox hbox1;
        
        private Gtk.VSeparator vseparator1;
        
        private Gtk.Button ParentsButton;
        
        private Gtk.HButtonBox hbuttonbox4;
        
        private Gtk.Button HusbandMoreButton;
        
        private Gtk.Button ScrapBookButton;
        
        private Gtk.Button HusbandFamiliesButton;
        
        private Gtk.Entry HusbandBornInEntry;
        
        private Gtk.Entry HusbandDateBornEntry;
        
        private Gtk.Button HusbandDateBornSourceButton;
        
        private Gtk.Image image439;
        
        private Gtk.Entry HusbandDateDiedEntry;
        
        private Gtk.Button HusbandDateDiedSourceButton;
        
        private Gtk.Image image440;
        
        private Gtk.Entry HusbandDiedInEntry;
        
        private Gtk.Entry HusbandNameEntry;
        
        private Gtk.Button HusbandNameSourceButton;
        
        private Gtk.Image image438;
        
        private Gtk.Label label10;
        
        private Gtk.Label label12;
        
        private Gtk.Label label18;
        
        private Gtk.Label label19;
        
        private Gtk.Button NameButton;
        
        private Gtk.Label SpouseNameLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.SpouseView
            Stetic.BinContainer.Attach(this);
            this.Name = "Gedcom.UI.GTK.Widgets.SpouseView";
            // Container child Gedcom.UI.GTK.Widgets.SpouseView.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(7)), ((uint)(3)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(12));
            this.table1.BorderWidth = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.hbox8 = new Gtk.HBox();
            this.hbox8.Name = "hbox8";
            this.hbox8.Spacing = 6;
            // Container child hbox8.Gtk.Box+BoxChild
            this.RemoveHusbandButton = new Gtk.Button();
            this.RemoveHusbandButton.CanFocus = true;
            this.RemoveHusbandButton.Name = "RemoveHusbandButton";
            // Container child RemoveHusbandButton.Gtk.Container+ContainerChild
            this.image413 = new Gtk.Image();
            this.image413.Name = "image413";
            this.image413.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
            this.RemoveHusbandButton.Add(this.image413);
            this.RemoveHusbandButton.Label = null;
            this.hbox8.Add(this.RemoveHusbandButton);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox8[this.RemoveHusbandButton]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox8.Gtk.Box+BoxChild
            this.AddHusbandButton = new Gtk.Button();
            this.AddHusbandButton.CanFocus = true;
            this.AddHusbandButton.Name = "AddHusbandButton";
            // Container child AddHusbandButton.Gtk.Container+ContainerChild
            this.image414 = new Gtk.Image();
            this.image414.Name = "image414";
            this.image414.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
            this.AddHusbandButton.Add(this.image414);
            this.AddHusbandButton.Label = null;
            this.hbox8.Add(this.AddHusbandButton);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox8[this.AddHusbandButton]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox8.Gtk.Box+BoxChild
            this.DeleteButton = new Gtk.Button();
            this.DeleteButton.CanFocus = true;
            this.DeleteButton.Name = "DeleteButton";
            // Container child DeleteButton.Gtk.Container+ContainerChild
            this.image415 = new Gtk.Image();
            this.image415.Name = "image415";
            this.image415.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-delete", Gtk.IconSize.Menu, 16);
            this.DeleteButton.Add(this.image415);
            this.DeleteButton.Label = null;
            this.hbox8.Add(this.DeleteButton);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox8[this.DeleteButton]));
            w6.Position = 2;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox8.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vseparator1 = new Gtk.VSeparator();
            this.vseparator1.Name = "vseparator1";
            this.hbox1.Add(this.vseparator1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
            w7.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.ParentsButton = new Gtk.Button();
            this.ParentsButton.CanFocus = true;
            this.ParentsButton.Name = "ParentsButton";
            this.ParentsButton.UseUnderline = true;
            // Container child ParentsButton.Gtk.Container+ContainerChild
            Gtk.Alignment w8 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w9 = new Gtk.HBox();
            w9.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w10 = new Gtk.Image();
            w10.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-up", Gtk.IconSize.Menu, 16);
            w9.Add(w10);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w12 = new Gtk.Label();
            w12.LabelProp = "Parents";
            w12.UseUnderline = true;
            w9.Add(w12);
            w8.Add(w9);
            this.ParentsButton.Add(w8);
            this.hbox1.Add(this.ParentsButton);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox1[this.ParentsButton]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            this.hbox8.Add(this.hbox1);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox8[this.hbox1]));
            w17.Position = 3;
            this.table1.Add(this.hbox8);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table1[this.hbox8]));
            w18.RightAttach = ((uint)(3));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbuttonbox4 = new Gtk.HButtonBox();
            this.hbuttonbox4.Name = "hbuttonbox4";
            this.hbuttonbox4.Spacing = 12;
            this.hbuttonbox4.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
            this.HusbandMoreButton = new Gtk.Button();
            this.HusbandMoreButton.CanFocus = true;
            this.HusbandMoreButton.Name = "HusbandMoreButton";
            this.HusbandMoreButton.UseUnderline = true;
            // Container child HusbandMoreButton.Gtk.Container+ContainerChild
            Gtk.Alignment w19 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w20 = new Gtk.HBox();
            w20.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w21 = new Gtk.Image();
            w21.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-edit", Gtk.IconSize.Button, 20);
            w20.Add(w21);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w23 = new Gtk.Label();
            w23.LabelProp = "More";
            w23.UseUnderline = true;
            w20.Add(w23);
            w19.Add(w20);
            this.HusbandMoreButton.Add(w19);
            this.hbuttonbox4.Add(this.HusbandMoreButton);
            Gtk.ButtonBox.ButtonBoxChild w27 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.HusbandMoreButton]));
            w27.Expand = false;
            w27.Fill = false;
            // Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
            this.ScrapBookButton = new Gtk.Button();
            this.ScrapBookButton.CanFocus = true;
            this.ScrapBookButton.Name = "ScrapBookButton";
            this.ScrapBookButton.UseUnderline = true;
            // Container child ScrapBookButton.Gtk.Container+ContainerChild
            Gtk.Alignment w28 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w29 = new Gtk.HBox();
            w29.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w30 = new Gtk.Image();
            w30.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-paste", Gtk.IconSize.Button, 20);
            w29.Add(w30);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w32 = new Gtk.Label();
            w32.LabelProp = "Scrapbook";
            w32.UseUnderline = true;
            w29.Add(w32);
            w28.Add(w29);
            this.ScrapBookButton.Add(w28);
            this.hbuttonbox4.Add(this.ScrapBookButton);
            Gtk.ButtonBox.ButtonBoxChild w36 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.ScrapBookButton]));
            w36.Position = 1;
            w36.Expand = false;
            w36.Fill = false;
            // Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
            this.HusbandFamiliesButton = new Gtk.Button();
            this.HusbandFamiliesButton.CanFocus = true;
            this.HusbandFamiliesButton.Name = "HusbandFamiliesButton";
            this.HusbandFamiliesButton.UseUnderline = true;
            // Container child HusbandFamiliesButton.Gtk.Container+ContainerChild
            Gtk.Alignment w37 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w38 = new Gtk.HBox();
            w38.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w39 = new Gtk.Image();
            w39.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-dialog-info", Gtk.IconSize.Button, 20);
            w38.Add(w39);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w41 = new Gtk.Label();
            w41.LabelProp = "Families";
            w41.UseUnderline = true;
            w38.Add(w41);
            w37.Add(w38);
            this.HusbandFamiliesButton.Add(w37);
            this.hbuttonbox4.Add(this.HusbandFamiliesButton);
            Gtk.ButtonBox.ButtonBoxChild w45 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.HusbandFamiliesButton]));
            w45.Position = 2;
            w45.Expand = false;
            w45.Fill = false;
            this.table1.Add(this.hbuttonbox4);
            Gtk.Table.TableChild w46 = ((Gtk.Table.TableChild)(this.table1[this.hbuttonbox4]));
            w46.TopAttach = ((uint)(6));
            w46.BottomAttach = ((uint)(7));
            w46.RightAttach = ((uint)(3));
            w46.YPadding = ((uint)(6));
            w46.XOptions = ((Gtk.AttachOptions)(4));
            w46.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandBornInEntry = new Gtk.Entry();
            this.HusbandBornInEntry.CanFocus = true;
            this.HusbandBornInEntry.Name = "HusbandBornInEntry";
            this.HusbandBornInEntry.IsEditable = true;
            this.HusbandBornInEntry.InvisibleChar = '●';
            this.table1.Add(this.HusbandBornInEntry);
            Gtk.Table.TableChild w47 = ((Gtk.Table.TableChild)(this.table1[this.HusbandBornInEntry]));
            w47.TopAttach = ((uint)(3));
            w47.BottomAttach = ((uint)(4));
            w47.LeftAttach = ((uint)(1));
            w47.RightAttach = ((uint)(2));
            w47.XOptions = ((Gtk.AttachOptions)(4));
            w47.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandDateBornEntry = new Gtk.Entry();
            this.HusbandDateBornEntry.CanFocus = true;
            this.HusbandDateBornEntry.Name = "HusbandDateBornEntry";
            this.HusbandDateBornEntry.IsEditable = true;
            this.HusbandDateBornEntry.InvisibleChar = '●';
            this.table1.Add(this.HusbandDateBornEntry);
            Gtk.Table.TableChild w48 = ((Gtk.Table.TableChild)(this.table1[this.HusbandDateBornEntry]));
            w48.TopAttach = ((uint)(2));
            w48.BottomAttach = ((uint)(3));
            w48.LeftAttach = ((uint)(1));
            w48.RightAttach = ((uint)(2));
            w48.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandDateBornSourceButton = new Gtk.Button();
            this.HusbandDateBornSourceButton.CanFocus = true;
            this.HusbandDateBornSourceButton.Name = "HusbandDateBornSourceButton";
            // Container child HusbandDateBornSourceButton.Gtk.Container+ContainerChild
            this.image439 = new Gtk.Image();
            this.image439.Name = "image439";
            this.image439.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            this.HusbandDateBornSourceButton.Add(this.image439);
            this.HusbandDateBornSourceButton.Label = null;
            this.table1.Add(this.HusbandDateBornSourceButton);
            Gtk.Table.TableChild w50 = ((Gtk.Table.TableChild)(this.table1[this.HusbandDateBornSourceButton]));
            w50.TopAttach = ((uint)(2));
            w50.BottomAttach = ((uint)(3));
            w50.LeftAttach = ((uint)(2));
            w50.RightAttach = ((uint)(3));
            w50.XOptions = ((Gtk.AttachOptions)(4));
            w50.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandDateDiedEntry = new Gtk.Entry();
            this.HusbandDateDiedEntry.CanFocus = true;
            this.HusbandDateDiedEntry.Name = "HusbandDateDiedEntry";
            this.HusbandDateDiedEntry.IsEditable = true;
            this.HusbandDateDiedEntry.InvisibleChar = '●';
            this.table1.Add(this.HusbandDateDiedEntry);
            Gtk.Table.TableChild w51 = ((Gtk.Table.TableChild)(this.table1[this.HusbandDateDiedEntry]));
            w51.TopAttach = ((uint)(4));
            w51.BottomAttach = ((uint)(5));
            w51.LeftAttach = ((uint)(1));
            w51.RightAttach = ((uint)(2));
            w51.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandDateDiedSourceButton = new Gtk.Button();
            this.HusbandDateDiedSourceButton.CanFocus = true;
            this.HusbandDateDiedSourceButton.Name = "HusbandDateDiedSourceButton";
            // Container child HusbandDateDiedSourceButton.Gtk.Container+ContainerChild
            this.image440 = new Gtk.Image();
            this.image440.Name = "image440";
            this.image440.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            this.HusbandDateDiedSourceButton.Add(this.image440);
            this.HusbandDateDiedSourceButton.Label = null;
            this.table1.Add(this.HusbandDateDiedSourceButton);
            Gtk.Table.TableChild w53 = ((Gtk.Table.TableChild)(this.table1[this.HusbandDateDiedSourceButton]));
            w53.TopAttach = ((uint)(4));
            w53.BottomAttach = ((uint)(5));
            w53.LeftAttach = ((uint)(2));
            w53.RightAttach = ((uint)(3));
            w53.XOptions = ((Gtk.AttachOptions)(4));
            w53.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandDiedInEntry = new Gtk.Entry();
            this.HusbandDiedInEntry.CanFocus = true;
            this.HusbandDiedInEntry.Name = "HusbandDiedInEntry";
            this.HusbandDiedInEntry.IsEditable = true;
            this.HusbandDiedInEntry.InvisibleChar = '●';
            this.table1.Add(this.HusbandDiedInEntry);
            Gtk.Table.TableChild w54 = ((Gtk.Table.TableChild)(this.table1[this.HusbandDiedInEntry]));
            w54.TopAttach = ((uint)(5));
            w54.BottomAttach = ((uint)(6));
            w54.LeftAttach = ((uint)(1));
            w54.RightAttach = ((uint)(2));
            w54.XOptions = ((Gtk.AttachOptions)(4));
            w54.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandNameEntry = new Gtk.Entry();
            this.HusbandNameEntry.CanFocus = true;
            this.HusbandNameEntry.Name = "HusbandNameEntry";
            this.HusbandNameEntry.IsEditable = true;
            this.HusbandNameEntry.InvisibleChar = '●';
            this.table1.Add(this.HusbandNameEntry);
            Gtk.Table.TableChild w55 = ((Gtk.Table.TableChild)(this.table1[this.HusbandNameEntry]));
            w55.TopAttach = ((uint)(1));
            w55.BottomAttach = ((uint)(2));
            w55.LeftAttach = ((uint)(1));
            w55.RightAttach = ((uint)(2));
            w55.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.HusbandNameSourceButton = new Gtk.Button();
            this.HusbandNameSourceButton.CanFocus = true;
            this.HusbandNameSourceButton.Name = "HusbandNameSourceButton";
            // Container child HusbandNameSourceButton.Gtk.Container+ContainerChild
            this.image438 = new Gtk.Image();
            this.image438.Name = "image438";
            this.image438.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            this.HusbandNameSourceButton.Add(this.image438);
            this.HusbandNameSourceButton.Label = null;
            this.table1.Add(this.HusbandNameSourceButton);
            Gtk.Table.TableChild w57 = ((Gtk.Table.TableChild)(this.table1[this.HusbandNameSourceButton]));
            w57.TopAttach = ((uint)(1));
            w57.BottomAttach = ((uint)(2));
            w57.LeftAttach = ((uint)(2));
            w57.RightAttach = ((uint)(3));
            w57.XOptions = ((Gtk.AttachOptions)(4));
            w57.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.Xalign = 1F;
            this.label10.LabelProp = "in:";
            this.table1.Add(this.label10);
            Gtk.Table.TableChild w58 = ((Gtk.Table.TableChild)(this.table1[this.label10]));
            w58.TopAttach = ((uint)(5));
            w58.BottomAttach = ((uint)(6));
            w58.XOptions = ((Gtk.AttachOptions)(4));
            w58.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.Xalign = 1F;
            this.label12.LabelProp = "in:";
            this.table1.Add(this.label12);
            Gtk.Table.TableChild w59 = ((Gtk.Table.TableChild)(this.table1[this.label12]));
            w59.TopAttach = ((uint)(3));
            w59.BottomAttach = ((uint)(4));
            w59.XOptions = ((Gtk.AttachOptions)(4));
            w59.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label18 = new Gtk.Label();
            this.label18.Name = "label18";
            this.label18.Xalign = 1F;
            this.label18.LabelProp = "Born:";
            this.table1.Add(this.label18);
            Gtk.Table.TableChild w60 = ((Gtk.Table.TableChild)(this.table1[this.label18]));
            w60.TopAttach = ((uint)(2));
            w60.BottomAttach = ((uint)(3));
            w60.XOptions = ((Gtk.AttachOptions)(4));
            w60.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label19 = new Gtk.Label();
            this.label19.Name = "label19";
            this.label19.Xalign = 1F;
            this.label19.LabelProp = "Died:";
            this.table1.Add(this.label19);
            Gtk.Table.TableChild w61 = ((Gtk.Table.TableChild)(this.table1[this.label19]));
            w61.TopAttach = ((uint)(4));
            w61.BottomAttach = ((uint)(5));
            w61.XOptions = ((Gtk.AttachOptions)(4));
            w61.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.NameButton = new Gtk.Button();
            this.NameButton.CanFocus = true;
            this.NameButton.Name = "NameButton";
            // Container child NameButton.Gtk.Container+ContainerChild
            this.SpouseNameLabel = new Gtk.Label();
            this.SpouseNameLabel.Name = "SpouseNameLabel";
            this.SpouseNameLabel.Xalign = 1F;
            this.SpouseNameLabel.LabelProp = "Name:";
            this.NameButton.Add(this.SpouseNameLabel);
            this.NameButton.Label = null;
            this.table1.Add(this.NameButton);
            Gtk.Table.TableChild w63 = ((Gtk.Table.TableChild)(this.table1[this.NameButton]));
            w63.TopAttach = ((uint)(1));
            w63.BottomAttach = ((uint)(2));
            w63.XOptions = ((Gtk.AttachOptions)(4));
            w63.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.NameButton.Clicked += new System.EventHandler(this.OnNameButton_Clicked);
            this.HusbandNameSourceButton.Clicked += new System.EventHandler(this.OnNameSourceButton_Clicked);
            this.HusbandDiedInEntry.Changed += new System.EventHandler(this.HusbandDied_Changed);
            this.HusbandDateDiedSourceButton.Clicked += new System.EventHandler(this.OnDateDiedSourceButton_Clicked);
            this.HusbandDateDiedEntry.Changed += new System.EventHandler(this.HusbandDied_Changed);
            this.HusbandDateBornSourceButton.Clicked += new System.EventHandler(this.OnDateBornSourceButton_Clicked);
            this.HusbandDateBornEntry.Changed += new System.EventHandler(this.HusbandBorn_Changed);
            this.HusbandBornInEntry.Changed += new System.EventHandler(this.HusbandBorn_Changed);
            this.HusbandMoreButton.Clicked += new System.EventHandler(this.OnMoreButton_Clicked);
            this.ScrapBookButton.Clicked += new System.EventHandler(this.OnScrapBookButton_Clicked);
            this.HusbandFamiliesButton.Clicked += new System.EventHandler(this.OnFamiliesButton_Clicked);
            this.RemoveHusbandButton.Clicked += new System.EventHandler(this.OnRemoveButton_Clicked);
            this.AddHusbandButton.Clicked += new System.EventHandler(this.OnAddButton_Clicked);
            this.DeleteButton.Clicked += new System.EventHandler(this.OnDeleteButton_Clicked);
            this.ParentsButton.Clicked += new System.EventHandler(this.OnParentsButton_Click);
        }
    }
}
