// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class SourceCitationView {
        
        private Gtk.Notebook Notebook;
        
        private Gtk.Table table1;
        
        private Gtk.ComboBox CertaintyComboBox;
        
        private Gtk.Entry DateEntry;
        
        private Gtk.Entry EventTypeEntry;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button ScrapbookButton;
        
        private Gtk.Button ViewMasterButton;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label5;
        
        private Gtk.Label label6;
        
        private Gtk.Label label7;
        
        private Gtk.Entry MasterSourceEntry;
        
        private Gtk.Entry PageEntry;
        
        private Gtk.Entry RoleEntry;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TextView TextTextView;
        
        private Gtk.Button SelectMasterSourceButton;
        
        private Gtk.Label label9;
        
        private Gedcom.UI.GTK.Widgets.NotesView NotesView;
        
        private Gtk.Label label10;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.SourceCitationView
            Stetic.BinContainer.Attach(this);
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.Widgets.SourceCitationView";
            // Container child Gedcom.UI.GTK.Widgets.SourceCitationView.Gtk.Container+ContainerChild
            this.Notebook = new Gtk.Notebook();
            this.Notebook.CanFocus = true;
            this.Notebook.Name = "Notebook";
            this.Notebook.CurrentPage = 1;
            this.Notebook.BorderWidth = ((uint)(6));
            // Container child Notebook.Gtk.Notebook+NotebookChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(4)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(12));
            this.table1.BorderWidth = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.CertaintyComboBox = new Gtk.ComboBox();
            this.CertaintyComboBox.Name = "CertaintyComboBox";
            this.table1.Add(this.CertaintyComboBox);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.CertaintyComboBox]));
            w1.TopAttach = ((uint)(3));
            w1.BottomAttach = ((uint)(4));
            w1.LeftAttach = ((uint)(3));
            w1.RightAttach = ((uint)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.DateEntry = new Gtk.Entry();
            this.DateEntry.CanFocus = true;
            this.DateEntry.Name = "DateEntry";
            this.DateEntry.IsEditable = true;
            this.DateEntry.InvisibleChar = '●';
            this.table1.Add(this.DateEntry);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.DateEntry]));
            w2.TopAttach = ((uint)(3));
            w2.BottomAttach = ((uint)(4));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.EventTypeEntry = new Gtk.Entry();
            this.EventTypeEntry.CanFocus = true;
            this.EventTypeEntry.Name = "EventTypeEntry";
            this.EventTypeEntry.IsEditable = true;
            this.EventTypeEntry.InvisibleChar = '●';
            this.table1.Add(this.EventTypeEntry);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.EventTypeEntry]));
            w3.TopAttach = ((uint)(2));
            w3.BottomAttach = ((uint)(3));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.ScrapbookButton = new Gtk.Button();
            this.ScrapbookButton.CanFocus = true;
            this.ScrapbookButton.Name = "ScrapbookButton";
            // Container child ScrapbookButton.Gtk.Container+ContainerChild
            Gtk.Alignment w4 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w5 = new Gtk.HBox();
            w5.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w6 = new Gtk.Image();
            w6.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-paste", Gtk.IconSize.Button, 20);
            w5.Add(w6);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w8 = new Gtk.Label();
            w8.LabelProp = "Scrapbook";
            w5.Add(w8);
            w4.Add(w5);
            this.ScrapbookButton.Add(w4);
            this.hbox1.Add(this.ScrapbookButton);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox1[this.ScrapbookButton]));
            w12.Position = 0;
            w12.Expand = false;
            w12.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.ViewMasterButton = new Gtk.Button();
            this.ViewMasterButton.CanFocus = true;
            this.ViewMasterButton.Name = "ViewMasterButton";
            this.ViewMasterButton.UseUnderline = true;
            // Container child ViewMasterButton.Gtk.Container+ContainerChild
            Gtk.Alignment w13 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w14 = new Gtk.HBox();
            w14.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w15 = new Gtk.Image();
            w15.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-find", Gtk.IconSize.Button, 20);
            w14.Add(w15);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w17 = new Gtk.Label();
            w17.LabelProp = "View Master Source";
            w17.UseUnderline = true;
            w14.Add(w17);
            w13.Add(w14);
            this.ViewMasterButton.Add(w13);
            this.hbox1.Add(this.ViewMasterButton);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox1[this.ViewMasterButton]));
            w21.Position = 1;
            w21.Fill = false;
            this.table1.Add(this.hbox1);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table1[this.hbox1]));
            w22.TopAttach = ((uint)(1));
            w22.BottomAttach = ((uint)(2));
            w22.LeftAttach = ((uint)(2));
            w22.RightAttach = ((uint)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = "Master Source:";
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w23.XOptions = ((Gtk.AttachOptions)(4));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = "Page:";
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w24.TopAttach = ((uint)(1));
            w24.BottomAttach = ((uint)(2));
            w24.XOptions = ((Gtk.AttachOptions)(4));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.LabelProp = "Event type:";
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w25.TopAttach = ((uint)(2));
            w25.BottomAttach = ((uint)(3));
            w25.XOptions = ((Gtk.AttachOptions)(4));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = "Role:";
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w26.TopAttach = ((uint)(2));
            w26.BottomAttach = ((uint)(3));
            w26.LeftAttach = ((uint)(2));
            w26.RightAttach = ((uint)(3));
            w26.XOptions = ((Gtk.AttachOptions)(4));
            w26.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 0F;
            this.label6.LabelProp = "Date:";
            this.table1.Add(this.label6);
            Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
            w27.TopAttach = ((uint)(3));
            w27.BottomAttach = ((uint)(4));
            w27.XOptions = ((Gtk.AttachOptions)(4));
            w27.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = "Certainty:";
            this.table1.Add(this.label7);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table1[this.label7]));
            w28.TopAttach = ((uint)(3));
            w28.BottomAttach = ((uint)(4));
            w28.LeftAttach = ((uint)(2));
            w28.RightAttach = ((uint)(3));
            w28.XOptions = ((Gtk.AttachOptions)(4));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.MasterSourceEntry = new Gtk.Entry();
            this.MasterSourceEntry.CanFocus = true;
            this.MasterSourceEntry.Name = "MasterSourceEntry";
            this.MasterSourceEntry.IsEditable = false;
            this.MasterSourceEntry.InvisibleChar = '●';
            this.table1.Add(this.MasterSourceEntry);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table1[this.MasterSourceEntry]));
            w29.LeftAttach = ((uint)(1));
            w29.RightAttach = ((uint)(3));
            w29.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.PageEntry = new Gtk.Entry();
            this.PageEntry.CanFocus = true;
            this.PageEntry.Name = "PageEntry";
            this.PageEntry.IsEditable = true;
            this.PageEntry.InvisibleChar = '●';
            this.table1.Add(this.PageEntry);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table1[this.PageEntry]));
            w30.TopAttach = ((uint)(1));
            w30.BottomAttach = ((uint)(2));
            w30.LeftAttach = ((uint)(1));
            w30.RightAttach = ((uint)(2));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.RoleEntry = new Gtk.Entry();
            this.RoleEntry.CanFocus = true;
            this.RoleEntry.Name = "RoleEntry";
            this.RoleEntry.IsEditable = true;
            this.RoleEntry.InvisibleChar = '●';
            this.table1.Add(this.RoleEntry);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table1[this.RoleEntry]));
            w31.TopAttach = ((uint)(2));
            w31.BottomAttach = ((uint)(3));
            w31.LeftAttach = ((uint)(3));
            w31.RightAttach = ((uint)(4));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.TextTextView = new Gtk.TextView();
            this.TextTextView.CanFocus = true;
            this.TextTextView.Name = "TextTextView";
            this.scrolledwindow1.Add(this.TextTextView);
            this.table1.Add(this.scrolledwindow1);
            Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table1[this.scrolledwindow1]));
            w33.TopAttach = ((uint)(4));
            w33.BottomAttach = ((uint)(5));
            w33.RightAttach = ((uint)(4));
            // Container child table1.Gtk.Table+TableChild
            this.SelectMasterSourceButton = new Gtk.Button();
            this.SelectMasterSourceButton.CanFocus = true;
            this.SelectMasterSourceButton.Name = "SelectMasterSourceButton";
            this.SelectMasterSourceButton.UseUnderline = true;
            // Container child SelectMasterSourceButton.Gtk.Container+ContainerChild
            Gtk.Alignment w34 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w35 = new Gtk.HBox();
            w35.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w36 = new Gtk.Image();
            w36.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            w35.Add(w36);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w38 = new Gtk.Label();
            w38.LabelProp = "Select Master Source";
            w38.UseUnderline = true;
            w35.Add(w38);
            w34.Add(w35);
            this.SelectMasterSourceButton.Add(w34);
            this.table1.Add(this.SelectMasterSourceButton);
            Gtk.Table.TableChild w42 = ((Gtk.Table.TableChild)(this.table1[this.SelectMasterSourceButton]));
            w42.LeftAttach = ((uint)(3));
            w42.RightAttach = ((uint)(4));
            w42.XOptions = ((Gtk.AttachOptions)(4));
            w42.YOptions = ((Gtk.AttachOptions)(4));
            this.Notebook.Add(this.table1);
            // Notebook tab
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = "Details";
            this.Notebook.SetTabLabel(this.table1, this.label9);
            this.label9.ShowAll();
            // Container child Notebook.Gtk.Notebook+NotebookChild
            this.NotesView = new Gedcom.UI.GTK.Widgets.NotesView();
            this.NotesView.Events = ((Gdk.EventMask)(256));
            this.NotesView.Name = "NotesView";
            this.NotesView.DataNotes = false;
            this.NotesView.ListOnly = false;
            this.NotesView.NoteOnly = false;
            this.Notebook.Add(this.NotesView);
            Gtk.Notebook.NotebookChild w44 = ((Gtk.Notebook.NotebookChild)(this.Notebook[this.NotesView]));
            w44.Position = 1;
            // Notebook tab
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.LabelProp = "Notes";
            this.Notebook.SetTabLabel(this.NotesView, this.label10);
            this.label10.ShowAll();
            this.Add(this.Notebook);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.SelectMasterSourceButton.Clicked += new System.EventHandler(this.OnSelectMasterSourceButton_Click);
            this.ScrapbookButton.Clicked += new System.EventHandler(this.OnScrapBookButton_Clicked);
            this.ViewMasterButton.Clicked += new System.EventHandler(this.OnViewMasterButton_Clicked);
            this.NotesView.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnNotesView_ShowSourceCitation);
            this.NotesView.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnNotesView_SelectNewNote);
        }
    }
}
