// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class FactDetailView {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label EventNameLabel;
        
        private Gtk.Notebook Notebook;
        
        private Gtk.Table table2;
        
        private Gtk.Entry AgencyEntry;
        
        private Gtk.Entry CauseEntry;
        
        private Gtk.Entry EventExtraEntry;
        
        private Gtk.Label EventExtraLabel;
        
        private Gtk.Button EventScrapbookButton;
        
        private Gtk.Entry EventTypeEntry;
        
        private Gtk.Label EventTypeLabel;
        
        private Gtk.Entry FactDateEntry;
        
        private Gtk.Button FactSourceButton;
        
        private Gtk.Image image441;
        
        private Gtk.Label label12;
        
        private Gtk.Label label13;
        
        private Gtk.Label label7;
        
        private Gtk.Label label8;
        
        private Gtk.Label label9;
        
        private Gtk.Entry ReligiousEntry;
        
        private Gtk.ScrolledWindow scrolledwindow4;
        
        private Gtk.TextView CommentTextView;
        
        private Gtk.Label label3;
        
        private Gedcom.UI.GTK.Widgets.AddressView AddressView;
        
        private Gtk.Label label4;
        
        private Gedcom.UI.GTK.Widgets.NotesView NotesView;
        
        private Gtk.Label label5;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.FactDetailView
            Stetic.BinContainer.Attach(this);
            this.Name = "Gedcom.UI.GTK.Widgets.FactDetailView";
            // Container child Gedcom.UI.GTK.Widgets.FactDetailView.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.EventNameLabel = new Gtk.Label();
            this.EventNameLabel.Name = "EventNameLabel";
            this.EventNameLabel.Xalign = 0F;
            this.EventNameLabel.LabelProp = "Event Name here";
            this.vbox1.Add(this.EventNameLabel);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.EventNameLabel]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.Notebook = new Gtk.Notebook();
            this.Notebook.CanFocus = true;
            this.Notebook.Name = "Notebook";
            this.Notebook.CurrentPage = 0;
            // Container child Notebook.Gtk.Notebook+NotebookChild
            this.table2 = new Gtk.Table(((uint)(7)), ((uint)(4)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(12));
            // Container child table2.Gtk.Table+TableChild
            this.AgencyEntry = new Gtk.Entry();
            this.AgencyEntry.CanFocus = true;
            this.AgencyEntry.Name = "AgencyEntry";
            this.AgencyEntry.IsEditable = true;
            this.AgencyEntry.InvisibleChar = '●';
            this.table2.Add(this.AgencyEntry);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table2[this.AgencyEntry]));
            w2.TopAttach = ((uint)(5));
            w2.BottomAttach = ((uint)(6));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.CauseEntry = new Gtk.Entry();
            this.CauseEntry.CanFocus = true;
            this.CauseEntry.Name = "CauseEntry";
            this.CauseEntry.IsEditable = true;
            this.CauseEntry.InvisibleChar = '●';
            this.table2.Add(this.CauseEntry);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table2[this.CauseEntry]));
            w3.TopAttach = ((uint)(4));
            w3.BottomAttach = ((uint)(5));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.EventExtraEntry = new Gtk.Entry();
            this.EventExtraEntry.CanFocus = true;
            this.EventExtraEntry.Name = "EventExtraEntry";
            this.EventExtraEntry.IsEditable = true;
            this.EventExtraEntry.InvisibleChar = '●';
            this.table2.Add(this.EventExtraEntry);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this.EventExtraEntry]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.EventExtraLabel = new Gtk.Label();
            this.EventExtraLabel.Name = "EventExtraLabel";
            this.EventExtraLabel.Xalign = 1F;
            this.EventExtraLabel.LabelProp = "Name:";
            this.table2.Add(this.EventExtraLabel);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table2[this.EventExtraLabel]));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.EventScrapbookButton = new Gtk.Button();
            this.EventScrapbookButton.CanFocus = true;
            this.EventScrapbookButton.Name = "EventScrapbookButton";
            this.EventScrapbookButton.UseUnderline = true;
            // Container child EventScrapbookButton.Gtk.Container+ContainerChild
            Gtk.Alignment w6 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w7 = new Gtk.HBox();
            w7.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w8 = new Gtk.Image();
            w8.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-paste", Gtk.IconSize.Menu, 16);
            w7.Add(w8);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w10 = new Gtk.Label();
            w10.LabelProp = "Scrapbook";
            w10.UseUnderline = true;
            w7.Add(w10);
            w6.Add(w7);
            this.EventScrapbookButton.Add(w6);
            this.table2.Add(this.EventScrapbookButton);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table2[this.EventScrapbookButton]));
            w14.LeftAttach = ((uint)(3));
            w14.RightAttach = ((uint)(4));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.EventTypeEntry = new Gtk.Entry();
            this.EventTypeEntry.CanFocus = true;
            this.EventTypeEntry.Name = "EventTypeEntry";
            this.EventTypeEntry.IsEditable = true;
            this.EventTypeEntry.InvisibleChar = '●';
            this.table2.Add(this.EventTypeEntry);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table2[this.EventTypeEntry]));
            w15.TopAttach = ((uint)(1));
            w15.BottomAttach = ((uint)(2));
            w15.LeftAttach = ((uint)(1));
            w15.RightAttach = ((uint)(2));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.EventTypeLabel = new Gtk.Label();
            this.EventTypeLabel.Name = "EventTypeLabel";
            this.EventTypeLabel.Xalign = 1F;
            this.EventTypeLabel.LabelProp = "Type / Classification:";
            this.table2.Add(this.EventTypeLabel);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table2[this.EventTypeLabel]));
            w16.TopAttach = ((uint)(1));
            w16.BottomAttach = ((uint)(2));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.FactDateEntry = new Gtk.Entry();
            this.FactDateEntry.CanFocus = true;
            this.FactDateEntry.Name = "FactDateEntry";
            this.FactDateEntry.IsEditable = true;
            this.FactDateEntry.InvisibleChar = '●';
            this.table2.Add(this.FactDateEntry);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table2[this.FactDateEntry]));
            w17.TopAttach = ((uint)(2));
            w17.BottomAttach = ((uint)(3));
            w17.LeftAttach = ((uint)(1));
            w17.RightAttach = ((uint)(2));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.FactSourceButton = new Gtk.Button();
            this.FactSourceButton.CanFocus = true;
            this.FactSourceButton.Name = "FactSourceButton";
            // Container child FactSourceButton.Gtk.Container+ContainerChild
            this.image441 = new Gtk.Image();
            this.image441.Name = "image441";
            this.image441.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            this.FactSourceButton.Add(this.image441);
            this.FactSourceButton.Label = null;
            this.table2.Add(this.FactSourceButton);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table2[this.FactSourceButton]));
            w19.LeftAttach = ((uint)(2));
            w19.RightAttach = ((uint)(3));
            w19.XOptions = ((Gtk.AttachOptions)(4));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.Xalign = 0F;
            this.label12.Yalign = 0F;
            this.label12.LabelProp = "Comment / Location:";
            this.table2.Add(this.label12);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table2[this.label12]));
            w20.TopAttach = ((uint)(3));
            w20.BottomAttach = ((uint)(4));
            w20.XOptions = ((Gtk.AttachOptions)(4));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label13 = new Gtk.Label();
            this.label13.Name = "label13";
            this.label13.Xalign = 1F;
            this.label13.LabelProp = "Date:";
            this.table2.Add(this.label13);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table2[this.label13]));
            w21.TopAttach = ((uint)(2));
            w21.BottomAttach = ((uint)(3));
            w21.XOptions = ((Gtk.AttachOptions)(4));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 1F;
            this.label7.LabelProp = "Cause:";
            this.table2.Add(this.label7);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table2[this.label7]));
            w22.TopAttach = ((uint)(4));
            w22.BottomAttach = ((uint)(5));
            w22.XOptions = ((Gtk.AttachOptions)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 1F;
            this.label8.LabelProp = "Responsible Agency:";
            this.table2.Add(this.label8);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table2[this.label8]));
            w23.TopAttach = ((uint)(5));
            w23.BottomAttach = ((uint)(6));
            w23.XOptions = ((Gtk.AttachOptions)(4));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.Xalign = 1F;
            this.label9.LabelProp = "Religious Affilliation:";
            this.table2.Add(this.label9);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table2[this.label9]));
            w24.TopAttach = ((uint)(6));
            w24.BottomAttach = ((uint)(7));
            w24.XOptions = ((Gtk.AttachOptions)(4));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.ReligiousEntry = new Gtk.Entry();
            this.ReligiousEntry.CanFocus = true;
            this.ReligiousEntry.Name = "ReligiousEntry";
            this.ReligiousEntry.IsEditable = true;
            this.ReligiousEntry.InvisibleChar = '●';
            this.table2.Add(this.ReligiousEntry);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table2[this.ReligiousEntry]));
            w25.TopAttach = ((uint)(6));
            w25.BottomAttach = ((uint)(7));
            w25.LeftAttach = ((uint)(1));
            w25.RightAttach = ((uint)(2));
            w25.XOptions = ((Gtk.AttachOptions)(4));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.scrolledwindow4 = new Gtk.ScrolledWindow();
            this.scrolledwindow4.CanFocus = true;
            this.scrolledwindow4.Name = "scrolledwindow4";
            this.scrolledwindow4.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow4.Gtk.Container+ContainerChild
            this.CommentTextView = new Gtk.TextView();
            this.CommentTextView.CanFocus = true;
            this.CommentTextView.Name = "CommentTextView";
            this.scrolledwindow4.Add(this.CommentTextView);
            this.table2.Add(this.scrolledwindow4);
            Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(this.table2[this.scrolledwindow4]));
            w27.TopAttach = ((uint)(3));
            w27.BottomAttach = ((uint)(4));
            w27.LeftAttach = ((uint)(1));
            w27.RightAttach = ((uint)(4));
            w27.YOptions = ((Gtk.AttachOptions)(4));
            this.Notebook.Add(this.table2);
            // Notebook tab
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = "Details";
            this.Notebook.SetTabLabel(this.table2, this.label3);
            this.label3.ShowAll();
            // Container child Notebook.Gtk.Notebook+NotebookChild
            this.AddressView = new Gedcom.UI.GTK.Widgets.AddressView();
            this.AddressView.Events = ((Gdk.EventMask)(256));
            this.AddressView.Name = "AddressView";
            this.Notebook.Add(this.AddressView);
            Gtk.Notebook.NotebookChild w29 = ((Gtk.Notebook.NotebookChild)(this.Notebook[this.AddressView]));
            w29.Position = 1;
            // Notebook tab
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = "Address";
            this.Notebook.SetTabLabel(this.AddressView, this.label4);
            this.label4.ShowAll();
            // Container child Notebook.Gtk.Notebook+NotebookChild
            this.NotesView = new Gedcom.UI.GTK.Widgets.NotesView();
            this.NotesView.Events = ((Gdk.EventMask)(256));
            this.NotesView.Name = "NotesView";
            this.NotesView.DataNotes = false;
            this.NotesView.ListOnly = false;
            this.NotesView.NoteOnly = false;
            this.Notebook.Add(this.NotesView);
            Gtk.Notebook.NotebookChild w30 = ((Gtk.Notebook.NotebookChild)(this.Notebook[this.NotesView]));
            w30.Position = 2;
            // Notebook tab
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = "Notes";
            this.Notebook.SetTabLabel(this.NotesView, this.label5);
            this.label5.ShowAll();
            this.vbox1.Add(this.Notebook);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox1[this.Notebook]));
            w31.Position = 1;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.FactSourceButton.Clicked += new System.EventHandler(this.OnFactSourceButton_Clicked);
            this.EventScrapbookButton.Clicked += new System.EventHandler(this.OnEventScrapbookButton_Clicked);
            this.NotesView.ShowSourceCitation += new System.EventHandler<Gedcom.UI.Common.SourceCitationArgs>(this.OnNotesView_ShowSourceCitation);
            this.NotesView.SelectNewNote += new System.EventHandler<Gedcom.UI.Common.NoteArgs>(this.OnNotesView_SelectNewNote);
        }
    }
}
