// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class FactView {
        
        private Gtk.Table table2;
        
        private Gtk.Button EventScrapbookButton;
        
        private Gtk.Entry FactDateEntry;
        
        private Gtk.Button FactMoreButton;
        
        private Gtk.Entry FactNameEntry;
        
        private Gtk.Button FactSourceButton;
        
        private Gtk.Image image441;
        
        private Gtk.ComboBox FactTypeCombo;
        
        private Gtk.HBox hbox2;
        
        private Gtk.ScrolledWindow scrolledwindow2;
        
        private Gtk.TreeView FactsTreeView;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Button NewFactButton;
        
        private Gtk.Label label12;
        
        private Gtk.Label label13;
        
        private Gtk.Label label8;
        
        private Gtk.ScrolledWindow scrolledwindow4;
        
        private Gtk.TextView CommentTextView;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.FactView
            Stetic.BinContainer.Attach(this);
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.Widgets.FactView";
            // Container child Gedcom.UI.GTK.Widgets.FactView.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(5)), ((uint)(6)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(12));
            // Container child table2.Gtk.Table+TableChild
            this.EventScrapbookButton = new Gtk.Button();
            this.EventScrapbookButton.CanFocus = true;
            this.EventScrapbookButton.Name = "EventScrapbookButton";
            this.EventScrapbookButton.UseUnderline = true;
            // Container child EventScrapbookButton.Gtk.Container+ContainerChild
            Gtk.Alignment w1 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w2 = new Gtk.HBox();
            w2.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w3 = new Gtk.Image();
            w3.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-paste", Gtk.IconSize.Menu, 16);
            w2.Add(w3);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w5 = new Gtk.Label();
            w2.Add(w5);
            w1.Add(w2);
            this.EventScrapbookButton.Add(w1);
            this.table2.Add(this.EventScrapbookButton);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table2[this.EventScrapbookButton]));
            w9.LeftAttach = ((uint)(5));
            w9.RightAttach = ((uint)(6));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.FactDateEntry = new Gtk.Entry();
            this.FactDateEntry.CanFocus = true;
            this.FactDateEntry.Name = "FactDateEntry";
            this.FactDateEntry.IsEditable = true;
            this.FactDateEntry.InvisibleChar = '●';
            this.table2.Add(this.FactDateEntry);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table2[this.FactDateEntry]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.FactMoreButton = new Gtk.Button();
            this.FactMoreButton.CanFocus = true;
            this.FactMoreButton.Name = "FactMoreButton";
            this.FactMoreButton.UseUnderline = true;
            // Container child FactMoreButton.Gtk.Container+ContainerChild
            Gtk.Alignment w11 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w12 = new Gtk.HBox();
            w12.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w13 = new Gtk.Image();
            w13.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-edit", Gtk.IconSize.Button, 20);
            w12.Add(w13);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w15 = new Gtk.Label();
            w15.LabelProp = "More";
            w15.UseUnderline = true;
            w12.Add(w15);
            w11.Add(w12);
            this.FactMoreButton.Add(w11);
            this.table2.Add(this.FactMoreButton);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table2[this.FactMoreButton]));
            w19.TopAttach = ((uint)(3));
            w19.BottomAttach = ((uint)(4));
            w19.XOptions = ((Gtk.AttachOptions)(4));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.FactNameEntry = new Gtk.Entry();
            this.FactNameEntry.CanFocus = true;
            this.FactNameEntry.Name = "FactNameEntry";
            this.FactNameEntry.IsEditable = true;
            this.FactNameEntry.InvisibleChar = '●';
            this.table2.Add(this.FactNameEntry);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table2[this.FactNameEntry]));
            w20.LeftAttach = ((uint)(2));
            w20.RightAttach = ((uint)(3));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.FactSourceButton = new Gtk.Button();
            this.FactSourceButton.CanFocus = true;
            this.FactSourceButton.Name = "FactSourceButton";
            // Container child FactSourceButton.Gtk.Container+ContainerChild
            this.image441 = new Gtk.Image();
            this.image441.Name = "image441";
            this.image441.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            this.FactSourceButton.Add(this.image441);
            this.FactSourceButton.Label = null;
            this.table2.Add(this.FactSourceButton);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table2[this.FactSourceButton]));
            w22.LeftAttach = ((uint)(4));
            w22.RightAttach = ((uint)(5));
            w22.XOptions = ((Gtk.AttachOptions)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.FactTypeCombo = Gtk.ComboBox.NewText();
            this.FactTypeCombo.Name = "FactTypeCombo";
            this.table2.Add(this.FactTypeCombo);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table2[this.FactTypeCombo]));
            w23.LeftAttach = ((uint)(1));
            w23.RightAttach = ((uint)(2));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.scrolledwindow2 = new Gtk.ScrolledWindow();
            this.scrolledwindow2.CanFocus = true;
            this.scrolledwindow2.Name = "scrolledwindow2";
            this.scrolledwindow2.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow2.Gtk.Container+ContainerChild
            this.FactsTreeView = new Gtk.TreeView();
            this.FactsTreeView.CanFocus = true;
            this.FactsTreeView.Name = "FactsTreeView";
            this.FactsTreeView.RulesHint = true;
            this.scrolledwindow2.Add(this.FactsTreeView);
            this.hbox2.Add(this.scrolledwindow2);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.hbox2[this.scrolledwindow2]));
            w25.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.NewFactButton = new Gtk.Button();
            this.NewFactButton.CanFocus = true;
            this.NewFactButton.Name = "NewFactButton";
            this.NewFactButton.UseStock = true;
            this.NewFactButton.UseUnderline = true;
            this.NewFactButton.Label = "gtk-new";
            this.vbox3.Add(this.NewFactButton);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox3[this.NewFactButton]));
            w26.Position = 0;
            w26.Expand = false;
            w26.Fill = false;
            this.hbox2.Add(this.vbox3);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
            w27.Position = 1;
            w27.Expand = false;
            w27.Fill = false;
            this.table2.Add(this.hbox2);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table2[this.hbox2]));
            w28.TopAttach = ((uint)(4));
            w28.BottomAttach = ((uint)(5));
            w28.RightAttach = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.Xalign = 0F;
            this.label12.Yalign = 0F;
            this.label12.LabelProp = "Comment / Location:";
            this.table2.Add(this.label12);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table2[this.label12]));
            w29.TopAttach = ((uint)(2));
            w29.BottomAttach = ((uint)(3));
            w29.XOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label13 = new Gtk.Label();
            this.label13.Name = "label13";
            this.label13.Xalign = 1F;
            this.label13.LabelProp = "Date:";
            this.table2.Add(this.label13);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table2[this.label13]));
            w30.TopAttach = ((uint)(1));
            w30.BottomAttach = ((uint)(2));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 1F;
            this.label8.LabelProp = "Fact Type:";
            this.table2.Add(this.label8);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table2[this.label8]));
            w31.XOptions = ((Gtk.AttachOptions)(4));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.scrolledwindow4 = new Gtk.ScrolledWindow();
            this.scrolledwindow4.CanFocus = true;
            this.scrolledwindow4.Name = "scrolledwindow4";
            this.scrolledwindow4.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow4.Gtk.Container+ContainerChild
            this.CommentTextView = new Gtk.TextView();
            this.CommentTextView.CanFocus = true;
            this.CommentTextView.Name = "CommentTextView";
            this.scrolledwindow4.Add(this.CommentTextView);
            this.table2.Add(this.scrolledwindow4);
            Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table2[this.scrolledwindow4]));
            w33.TopAttach = ((uint)(2));
            w33.BottomAttach = ((uint)(4));
            w33.LeftAttach = ((uint)(1));
            w33.RightAttach = ((uint)(6));
            w33.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.FactsTreeView.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnFactsTreeView_ButtonPressEvent);
            this.NewFactButton.Clicked += new System.EventHandler(this.OnNewFactButton_Clicked);
            this.FactSourceButton.Clicked += new System.EventHandler(this.OnFactSourceButton_Clicked);
            this.FactMoreButton.Clicked += new System.EventHandler(this.OnFactMoreButton_Clicked);
            this.EventScrapbookButton.Clicked += new System.EventHandler(this.OnEventScrapbookButton_Clicked);
        }
    }
}
