// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class MarriageView {
        
        private Gtk.Table table3;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Label label15;
        
        private Gtk.ComboBox BeginingStatusComboBox;
        
        private Gtk.Label label31;
        
        private Gtk.Label label32;
        
        private Gtk.HButtonBox MarriageButtonBox;
        
        private Gtk.Button MarriageMoreButton;
        
        private Gtk.Button MarriageScrapbookButton;
        
        private Gtk.Entry MarriageDateEntry;
        
        private Gtk.Entry MarriageLocationEntry;
        
        private Gtk.Button MarriageSourceButton;
        
        private Gtk.Image image442;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.MarriageView
            Stetic.BinContainer.Attach(this);
            this.Name = "Gedcom.UI.GTK.Widgets.MarriageView";
            // Container child Gedcom.UI.GTK.Widgets.MarriageView.Gtk.Container+ContainerChild
            this.table3 = new Gtk.Table(((uint)(2)), ((uint)(4)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(12));
            this.table3.BorderWidth = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 12;
            // Container child hbox4.Gtk.Box+BoxChild
            this.label15 = new Gtk.Label();
            this.label15.Name = "label15";
            this.label15.Xalign = 1F;
            this.label15.LabelProp = "Begining Status:";
            this.hbox4.Add(this.label15);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox4[this.label15]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.BeginingStatusComboBox = Gtk.ComboBox.NewText();
            this.BeginingStatusComboBox.AppendText("Single");
            this.BeginingStatusComboBox.AppendText("Private");
            this.BeginingStatusComboBox.AppendText("Partners");
            this.BeginingStatusComboBox.AppendText("Other");
            this.BeginingStatusComboBox.AppendText("Unknown");
            this.BeginingStatusComboBox.Name = "BeginingStatusComboBox";
            this.BeginingStatusComboBox.Active = 4;
            this.hbox4.Add(this.BeginingStatusComboBox);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox4[this.BeginingStatusComboBox]));
            w2.Position = 1;
            this.table3.Add(this.hbox4);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table3[this.hbox4]));
            w3.LeftAttach = ((uint)(3));
            w3.RightAttach = ((uint)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.label31 = new Gtk.Label();
            this.label31.Name = "label31";
            this.label31.Xalign = 0F;
            this.label31.LabelProp = "Marriage Date:";
            this.table3.Add(this.label31);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table3[this.label31]));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.label32 = new Gtk.Label();
            this.label32.Name = "label32";
            this.label32.Xalign = 0F;
            this.label32.LabelProp = "Marriage Location:";
            this.table3.Add(this.label32);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table3[this.label32]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.MarriageButtonBox = new Gtk.HButtonBox();
            this.MarriageButtonBox.Name = "MarriageButtonBox";
            this.MarriageButtonBox.Spacing = 12;
            this.MarriageButtonBox.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child MarriageButtonBox.Gtk.ButtonBox+ButtonBoxChild
            this.MarriageMoreButton = new Gtk.Button();
            this.MarriageMoreButton.CanFocus = true;
            this.MarriageMoreButton.Name = "MarriageMoreButton";
            this.MarriageMoreButton.UseUnderline = true;
            // Container child MarriageMoreButton.Gtk.Container+ContainerChild
            Gtk.Alignment w6 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w7 = new Gtk.HBox();
            w7.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w8 = new Gtk.Image();
            w8.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-edit", Gtk.IconSize.Button, 20);
            w7.Add(w8);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w10 = new Gtk.Label();
            w10.LabelProp = "More";
            w10.UseUnderline = true;
            w7.Add(w10);
            w6.Add(w7);
            this.MarriageMoreButton.Add(w6);
            this.MarriageButtonBox.Add(this.MarriageMoreButton);
            Gtk.ButtonBox.ButtonBoxChild w14 = ((Gtk.ButtonBox.ButtonBoxChild)(this.MarriageButtonBox[this.MarriageMoreButton]));
            w14.Expand = false;
            w14.Fill = false;
            // Container child MarriageButtonBox.Gtk.ButtonBox+ButtonBoxChild
            this.MarriageScrapbookButton = new Gtk.Button();
            this.MarriageScrapbookButton.CanFocus = true;
            this.MarriageScrapbookButton.Name = "MarriageScrapbookButton";
            this.MarriageScrapbookButton.UseUnderline = true;
            // Container child MarriageScrapbookButton.Gtk.Container+ContainerChild
            Gtk.Alignment w15 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w16 = new Gtk.HBox();
            w16.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w17 = new Gtk.Image();
            w17.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-paste", Gtk.IconSize.Button, 20);
            w16.Add(w17);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w19 = new Gtk.Label();
            w19.LabelProp = "Scrapbook";
            w19.UseUnderline = true;
            w16.Add(w19);
            w15.Add(w16);
            this.MarriageScrapbookButton.Add(w15);
            this.MarriageButtonBox.Add(this.MarriageScrapbookButton);
            Gtk.ButtonBox.ButtonBoxChild w23 = ((Gtk.ButtonBox.ButtonBoxChild)(this.MarriageButtonBox[this.MarriageScrapbookButton]));
            w23.Position = 1;
            w23.Expand = false;
            w23.Fill = false;
            this.table3.Add(this.MarriageButtonBox);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table3[this.MarriageButtonBox]));
            w24.TopAttach = ((uint)(1));
            w24.BottomAttach = ((uint)(2));
            w24.LeftAttach = ((uint)(3));
            w24.RightAttach = ((uint)(4));
            w24.XOptions = ((Gtk.AttachOptions)(4));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.MarriageDateEntry = new Gtk.Entry();
            this.MarriageDateEntry.CanFocus = true;
            this.MarriageDateEntry.Name = "MarriageDateEntry";
            this.MarriageDateEntry.IsEditable = true;
            this.MarriageDateEntry.InvisibleChar = '●';
            this.table3.Add(this.MarriageDateEntry);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table3[this.MarriageDateEntry]));
            w25.LeftAttach = ((uint)(1));
            w25.RightAttach = ((uint)(2));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.MarriageLocationEntry = new Gtk.Entry();
            this.MarriageLocationEntry.CanFocus = true;
            this.MarriageLocationEntry.Name = "MarriageLocationEntry";
            this.MarriageLocationEntry.IsEditable = true;
            this.MarriageLocationEntry.InvisibleChar = '●';
            this.table3.Add(this.MarriageLocationEntry);
            Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table3[this.MarriageLocationEntry]));
            w26.TopAttach = ((uint)(1));
            w26.BottomAttach = ((uint)(2));
            w26.LeftAttach = ((uint)(1));
            w26.RightAttach = ((uint)(3));
            w26.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.MarriageSourceButton = new Gtk.Button();
            this.MarriageSourceButton.CanFocus = true;
            this.MarriageSourceButton.Name = "MarriageSourceButton";
            // Container child MarriageSourceButton.Gtk.Container+ContainerChild
            this.image442 = new Gtk.Image();
            this.image442.Name = "image442";
            this.image442.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-index", Gtk.IconSize.Button, 20);
            this.MarriageSourceButton.Add(this.image442);
            this.MarriageSourceButton.Label = null;
            this.table3.Add(this.MarriageSourceButton);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table3[this.MarriageSourceButton]));
            w28.LeftAttach = ((uint)(2));
            w28.RightAttach = ((uint)(3));
            w28.XOptions = ((Gtk.AttachOptions)(4));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.MarriageSourceButton.Clicked += new System.EventHandler(this.OnMarriageSourceButton_Clicked);
            this.MarriageLocationEntry.Changed += new System.EventHandler(this.Marriage_Changed);
            this.MarriageDateEntry.Changed += new System.EventHandler(this.Marriage_Changed);
            this.MarriageMoreButton.Clicked += new System.EventHandler(this.OnMarriageMoreButton_Clicked);
            this.MarriageScrapbookButton.Clicked += new System.EventHandler(this.OnMarriageScrapbookButton_Clicked);
        }
    }
}
