// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gedcom.UI.GTK.Widgets {
    
    
    public partial class SourceCitationList {
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView SourceCitationTreeView;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Button NewSourceCitationButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gedcom.UI.GTK.Widgets.SourceCitationList
            Stetic.BinContainer.Attach(this);
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Gedcom.UI.GTK.Widgets.SourceCitationList";
            // Container child Gedcom.UI.GTK.Widgets.SourceCitationList.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            this.vbox1.BorderWidth = ((uint)(6));
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.HscrollbarPolicy = ((Gtk.PolicyType)(2));
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.SourceCitationTreeView = new Gtk.TreeView();
            this.SourceCitationTreeView.CanFocus = true;
            this.SourceCitationTreeView.Name = "SourceCitationTreeView";
            this.SourceCitationTreeView.Reorderable = true;
            this.SourceCitationTreeView.RulesHint = true;
            this.SourceCitationTreeView.SearchColumn = 0;
            this.scrolledwindow1.Add(this.SourceCitationTreeView);
            this.hbox1.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.scrolledwindow1]));
            w2.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.NewSourceCitationButton = new Gtk.Button();
            this.NewSourceCitationButton.CanFocus = true;
            this.NewSourceCitationButton.Name = "NewSourceCitationButton";
            this.NewSourceCitationButton.UseStock = true;
            this.NewSourceCitationButton.UseUnderline = true;
            this.NewSourceCitationButton.Label = "gtk-new";
            this.vbox2.Add(this.NewSourceCitationButton);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.NewSourceCitationButton]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            this.hbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w5.Position = 0;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.SourceCitationTreeView.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnSourceCitationTreeView_ButtonPressEvent);
            this.NewSourceCitationButton.Clicked += new System.EventHandler(this.OnNewSourceCitationButton_Clicked);
        }
    }
}
